# 01 — Data Understanding and Quality Audit

**Mục tiêu:** hiểu dữ liệu gốc, thống kê cấu trúc, kiểm tra khóa/quan hệ, duplicate, review bất thường và chất lượng dữ liệu trước khi xử lý.

### Cell code 01: Chuẩn bị môi trường và kết nối Drive

- **Mục đích:** Nạp các thư viện cơ bản, kết nối Google Drive và xác định nơi lưu dữ liệu.
- **Vì sao:** Các cell sau cần dùng chung thư viện và đường dẫn dữ liệu.
- **Giúp ích:** Notebook truy cập được dữ liệu Olist trên Drive.

In [1]:

from google.colab import drive
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

drive.mount("/content/drive")

DRIVE_ROOT = Path("/content/drive/MyDrive")
print("Đã kết nối Google Drive:", DRIVE_ROOT.exists())

# Đường dẫn chuẩn dùng xuyên suốt pipeline
DATA_DIR = DRIVE_ROOT / "BigData" / "DA-BigData" / "code" / "data"
PROCESSED_DIR = DATA_DIR / "processed"
DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

Mounted at /content/drive
Đã kết nối Google Drive: True

### Cell code 02: Tải bộ dữ liệu Olist

- **Mục đích:** Tạo thư mục data, tải bộ Olist và chép các tệp CSV vào đó.
- **Vì sao:** Cần một nguồn dữ liệu thống nhất để chạy các bước kiểm tra.
- **Giúp ích:** Có đủ các bảng gốc trong một thư mục để đọc và nối.

In [2]:
%pip -q install kagglehub

import kagglehub
import shutil

DATA_DIR = DRIVE_ROOT/"BigData"/"DA-BigData" /"code" / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

source_dir = Path(
    kagglehub.dataset_download("olistbr/brazilian-ecommerce")
)

csv_files = list(source_dir.rglob("*.csv"))

if len(csv_files) != 9:
    raise RuntimeError(f"Chỉ tìm thấy {len(csv_files)} tệp CSV; cần kiểm tra bản tải xuống.")

for source_file in csv_files:
    shutil.copy2(source_file, DATA_DIR / source_file.name)

print(f"Đã lưu {len(csv_files)} tệp CSV vào: {DATA_DIR}")
for file in sorted(DATA_DIR.glob("*.csv")):
    print(file.name)

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Đã lưu 9 tệp CSV vào: /content/drive/MyDrive/BigData/DA-BigData/code/data
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

### Cell code 03: Tổng quan các bảng

- **Mục đích:** Đọc các bảng bằng Dask, thống kê số dòng, số cột, dung lượng và trực quan hóa.
- **Vì sao:** Kích thước mỗi bảng khác nhau, cần biết trước khi phân tích chi tiết.
- **Giúp ích:** Xác định bảng nào lớn và kiểm tra đã nạp đủ tệp.

In [3]:
%pip -q install "dask[dataframe]" hvplot panel

import dask
import dask.dataframe as dd
import hvplot.pandas
import panel as pn

pn.extension()
pn.config.theme = "default"

def black_chart_text(plot, element):
    figure = plot.state
    figure.background_fill_color = "white"
    figure.border_fill_color = "white"
    figure.title.text_color = "black"

    for axis in list(figure.xaxis) + list(figure.yaxis):
        axis.axis_label_text_color = "black"
        axis.major_label_text_color = "black"

tables = {
    path.stem: dd.read_csv(
        str(path),
        blocksize="32MB",
        sample=2_000_000,
        assume_missing=True
    )
    for path in sorted(DATA_DIR.glob("*.csv"))
}

names = list(tables)
row_counts = dask.compute(
    *[tables[name].map_partitions(len).sum() for name in names]
)

table_summary = pd.DataFrame([
    {
        "Bảng": name,
        "Số dòng": row_count,
        "Số cột": len(tables[name].columns),
        "Số phân vùng": tables[name].npartitions,
        "Dung lượng tệp (MB)": round(
            (DATA_DIR / f"{name}.csv").stat().st_size / 1024**2, 2
        )
    }
    for name, row_count in zip(names, row_counts)
])

display(
    pn.Column(
        table_summary.hvplot.table(width=1000, height=310),
        table_summary.hvplot.bar(
            x="Bảng",
            y="Số dòng",
            width=1000,
            height=400,
            rot=45,
            title="Số dòng của từng bảng"
        ).opts(hooks=[black_chart_text]),
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.6/180.6 kB 4.4 MB/s eta 0:00:00

/tmp/ipykernel_2812/4164959781.py:8: UserWarning: Using Panel interactively in Colab notebooks requires the jupyter_bokeh package to be installed. Install it with:

    !pip install jupyter_bokeh

and try again.
  pn.extension()

Column(styles={'background': 'white', ...})
    [0] HoloViews(Table, height=310, width=1000)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=1000)

### Cell code 04: Thống kê từng cột

- **Mục đích:** Xem kiểu dữ liệu, số giá trị thiếu và số giá trị khác nhau của từng cột.
- **Vì sao:** Những thông tin này giúp phát hiện cột khó nối hoặc cần xử lý.
- **Giúp ích:** Có cơ sở chọn khóa và các biến sẽ dùng về sau.

In [4]:
tabs = []

for name, df in tables.items():
    missing_counts, unique_counts = dask.compute(
        df.isna().sum(),
        df.nunique(dropna=True)
    )

    column_summary = pd.DataFrame({
        "Cột": df.columns,
        "Kiểu dữ liệu": df.dtypes.astype(str).values,
        "Số giá trị thiếu": missing_counts.reindex(df.columns).values,
        "Tỷ lệ thiếu (%)": (
            missing_counts.reindex(df.columns) / table_summary.loc[
                table_summary["Bảng"] == name, "Số dòng"
            ].iloc[0] * 100
        ).round(2).values,
        "Số giá trị khác nhau": unique_counts.reindex(df.columns).values
    })

    tabs.append((
        name,
        pn.Column(
            column_summary.hvplot.table(width=1000, height=360),
            column_summary.hvplot.bar(
                x="Cột",
                y="Tỷ lệ thiếu (%)",
                width=1000,
                height=360,
                rot=45,
                title=f"Tỷ lệ thiếu theo cột: {name}"
            ).opts(hooks=[black_chart_text]),
            styles={"background": "white", "color": "black", "padding": "12px"}
        )
    ))

display(pn.Tabs(*tabs))

Tabs
    [0] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [1] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [2] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [3] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [4] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [5] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [6] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [7] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)
    [8] Column(styles={'background': 'white', ...})
        [0] HoloViews(Table, height=360, width=1000)
        [1] HoloViews(Bars, height=360, sizing_mode='fixed', width=1000)

### Cell code 05: Sơ đồ quan hệ giữa các bảng

- **Mục đích:** Kiểm tra các khóa nối và vẽ sơ đồ quan hệ bằng số liệu thực tế.
- **Vì sao:** Nối sai quan hệ một–nhiều có thể làm tăng số dòng giả.
- **Giúp ích:** Hiểu cách ghép các bảng mà không đếm trùng giao dịch.

In [5]:
import math
import dask
import pandas as pd
import networkx as nx
import holoviews as hv
import hvplot.pandas
import hvplot.networkx as hvnx
import panel as pn

pn.extension("tabulator")

names = {
    "olist_customers_dataset": "Customers",
    "olist_orders_dataset": "Orders",
    "olist_order_items_dataset": "Items",
    "olist_order_payments_dataset": "Payments",
    "olist_order_reviews_dataset": "Reviews",
    "olist_products_dataset": "Products",
    "olist_sellers_dataset": "Sellers",
    "product_category_name_translation": "Categories",
    "olist_geolocation_dataset": "Geolocation"
}

relations = [
    ("olist_orders_dataset", "olist_customers_dataset", "customer_id", "customer_id"),
    ("olist_order_items_dataset", "olist_orders_dataset", "order_id", "order_id"),
    ("olist_order_payments_dataset", "olist_orders_dataset", "order_id", "order_id"),
    ("olist_order_reviews_dataset", "olist_orders_dataset", "order_id", "order_id"),
    ("olist_order_items_dataset", "olist_products_dataset", "product_id", "product_id"),
    ("olist_order_items_dataset", "olist_sellers_dataset", "seller_id", "seller_id"),
    ("olist_products_dataset", "product_category_name_translation", "product_category_name", "product_category_name"),
    ("olist_customers_dataset", "olist_geolocation_dataset", "customer_zip_code_prefix", "geolocation_zip_code_prefix"),
    ("olist_sellers_dataset", "olist_geolocation_dataset", "seller_zip_code_prefix", "geolocation_zip_code_prefix")
]

required_keys = {
    (table_name, key)
    for source, target, source_key, target_key in relations
    for table_name, key in [(source, source_key), (target, target_key)]
}

tasks = {}

for table_name, df in tables.items():
    tasks[("rows", table_name)] = df.map_partitions(len).sum()

for table_name, key in sorted(required_keys):
    series = tables[table_name][key].dropna()

    if "zip_code_prefix" in key:
        series = series.astype("float64").astype("int64")
    else:
        series = series.astype("string")

    tasks[("valid", table_name, key)] = series.count()
    tasks[("unique", table_name, key)] = series.drop_duplicates()

results = dict(zip(tasks, dask.compute(*tasks.values())))

rows = {
    table_name: int(results[("rows", table_name)])
    for table_name in tables
}

key_sets = {
    (table_name, key): set(results[("unique", table_name, key)].tolist())
    for table_name, key in required_keys
}

stats = []

for source, target, source_key, target_key in relations:
    source_values = key_sets[(source, source_key)]
    target_values = key_sets[(target, target_key)]
    matched = len(source_values & target_values)

    stats.append({
        "Bảng nguồn": names[source],
        "Bảng đích": names[target],
        "Khóa nguồn": source_key,
        "Khóa đích": target_key,
        "Dòng nguồn": rows[source],
        "Dòng đích": rows[target],
        "Khóa nguồn duy nhất": len(source_values),
        "Khóa nguồn trùng": int(results[("valid", source, source_key)]) - len(source_values),
        "Khóa đích trùng": int(results[("valid", target, target_key)]) - len(target_values),
        "Khóa khớp": matched,
        "Khóa nguồn không khớp": len(source_values) - matched,
        "Tỷ lệ khớp (%)": round(100 * matched / len(source_values), 2) if source_values else 0
    })

relation_summary = pd.DataFrame(stats)

node_summary = pd.DataFrame([
    {"Bảng": names[table_name], "Số dòng": count}
    for table_name, count in rows.items()
])

max_matched = max(relation_summary["Khóa khớp"].max(), 1)
graph = nx.Graph()

for table_name in tables:
    graph.add_node(names[table_name])

for item in stats:
    matched = item["Khóa khớp"]

    graph.add_edge(
        item["Bảng nguồn"],
        item["Bảng đích"],
        do_rong=1.5 + 5 * math.log1p(matched) / math.log1p(max_matched),
        khoa_khop=matched
    )

main_positions = {
    "Customers": (0, 0),
    "Orders": (2.5, 0),
    "Items": (5, 0),
    "Payments": (2.5, 1.7),
    "Reviews": (2.5, -1.7),
    "Products": (7.5, 1.2),
    "Sellers": (7.5, -1.2),
    "Categories": (10, 1.2)
}

geo_positions = {
    "Customers": (0, 1),
    "Sellers": (0, -1),
    "Geolocation": (3, 0)
}

main_graph = graph.subgraph(main_positions).copy()
geo_graph = graph.subgraph(geo_positions).copy()

main_plot = hvnx.draw(
    main_graph,
    pos=main_positions,
    with_labels=True,
    node_size=5000,
    node_color="#BFDBFE",
    edge_color="#2563EB",
    edge_width=hv.dim("do_rong"),
    font_color="#000000",
    font_size="11pt",
    width=1150,
    height=480
).opts(
    bgcolor="#ffffff",
    xaxis=None,
    yaxis=None,
    padding=0.18
)

geo_plot = hvnx.draw(
    geo_graph,
    pos=geo_positions,
    with_labels=True,
    node_size=6000,
    node_color="#DDD6FE",
    edge_color="#7C3AED",
    edge_width=hv.dim("do_rong"),
    font_color="#000000",
    font_size="11pt",
    width=750,
    height=330
).opts(
    bgcolor="#ffffff",
    xaxis=None,
    yaxis=None,
    padding=0.22
)

black_text = {
    "color": "#000000",
    "background": "#ffffff"
}

table_css = ["""
:host .tabulator,
:host .tabulator * {
    color: #000000 !important;
    background-color: #ffffff !important;
}
"""]

display(
    pn.Column(
        pn.pane.Markdown("## Quan hệ giữa các bảng Olist", styles=black_text),
        pn.pane.Markdown(
            "Đường càng dày, số khóa khác nhau xuất hiện ở cả hai bảng càng lớn.",
            styles=black_text
        ),
        main_plot,
        pn.pane.Markdown("### Quan hệ với bảng Geolocation", styles=black_text),
        geo_plot,
        pn.pane.Markdown("### Số dòng thực tế", styles=black_text),
        pn.widgets.Tabulator(
            node_summary,
            show_index=False,
            theme="bootstrap5",
            width=600,
            height=285,
            stylesheets=table_css
        ),
        pn.pane.Markdown("### Kiểm tra khóa nối", styles=black_text),
        pn.widgets.Tabulator(
            relation_summary,
            show_index=False,
            theme="bootstrap5",
            width=1500,
            height=340,
            stylesheets=table_css
        ),
        styles={"background": "#ffffff", "padding": "20px"}
    )
)

/tmp/ipykernel_2812/3961459343.py:10: UserWarning: Using Panel interactively in Colab notebooks requires the jupyter_bokeh package to be installed. Install it with:

    !pip install jupyter_bokeh

and try again.
  pn.extension("tabulator")

Column(styles={'background': '#ffffff', ...})
    [0] Markdown(str, styles={'color': '#000000', ...})
    [1] Markdown(str, styles={'color': '#000000', ...})
    [2] HoloViews(Overlay, height=480, sizing_mode='fixed', width=1150)
    [3] Markdown(str, styles={'color': '#000000', ...})
    [4] HoloViews(Overlay, height=330, sizing_mode='fixed', width=750)
    [5] Markdown(str, styles={'color': '#000000', ...})
    [6] Tabulator(height=285, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=          Bảng  ..., width=600)
    [7] Markdown(str, styles={'color': '#000000', ...})
    [8] Tabulator(height=340, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=  Bảng nguồn  ..., width=1500)

### Cell code 05A: Trực quan hóa chất lượng quan hệ giữa các bảng

- **Mục đích:** Trực quan hóa tỷ lệ khóa khớp và số khóa nguồn không khớp giữa các bảng.
- **Vì sao:** Bảng `relation_summary` có nhiều cột nên khó nhận ra ngay quan hệ nào có vấn đề.
- **Giúp ích:** Nhìn nhanh chất lượng khóa nối trước khi ghép dữ liệu.

In [23]:
relation_plot = relation_summary.copy()

relation_plot["Quan hệ"] = (
    relation_plot["Bảng nguồn"].astype(str)
    + " → "
    + relation_plot["Bảng đích"].astype(str)
)

relation_plot["Tỷ lệ khớp (%)"] = pd.to_numeric(
    relation_plot["Tỷ lệ khớp (%)"],
    errors="coerce"
).fillna(0)

relation_plot["Khóa nguồn không khớp"] = pd.to_numeric(
    relation_plot["Khóa nguồn không khớp"],
    errors="coerce"
).fillna(0)

match_rate_plot = relation_plot.hvplot.bar(
    x="Quan hệ",
    y="Tỷ lệ khớp (%)",
    width=1100,
    height=430,
    rot=45,
    ylim=(0, 105),
    title="Tỷ lệ khóa nguồn khớp với bảng đích",
    xlabel="Quan hệ giữa các bảng",
    ylabel="Tỷ lệ khớp (%)"
).opts(
    hooks=[black_chart_text]
)

unmatched_plot = relation_plot.hvplot.bar(
    x="Quan hệ",
    y="Khóa nguồn không khớp",
    width=1100,
    height=430,
    rot=45,
    title="Số khóa nguồn không tìm thấy ở bảng đích",
    xlabel="Quan hệ giữa các bảng",
    ylabel="Số khóa không khớp"
).opts(
    hooks=[black_chart_text]
)

display(match_rate_plot)
display(unmatched_plot)

:Bars   [Quan hệ]   (Tỷ lệ khớp (%))

:Bars   [Quan hệ]   (Khóa nguồn không khớp)

`Thống kê giá trị tùng lặp`

### Cell code 06: Kiểm tra trùng lặp toàn bộ bảng

- **Mục đích:** Đếm dòng trùng hoàn toàn, khóa định danh trùng và khóa lặp theo quan hệ một–nhiều.
- **Vì sao:** Một mã đơn duy nhất khác với việc nhiều sản phẩm cùng thuộc một đơn.
- **Giúp ích:** Phân biệt lỗi dữ liệu với sự lặp hợp lệ trước khi làm sạch.

In [7]:
import dask
import pandas as pd
import panel as pn

pn.extension("tabulator")

key_rules = {
    "olist_customers_dataset": {
        "id": ["customer_id"],
        "repeated": [["customer_unique_id"]]
    },
    "olist_geolocation_dataset": {
        "id": None,
        "repeated": [["geolocation_zip_code_prefix"]]
    },
    "olist_order_items_dataset": {
        "id": ["order_id", "order_item_id"],
        "repeated": [["order_id"], ["product_id"], ["seller_id"]]
    },
    "olist_order_payments_dataset": {
        "id": ["order_id", "payment_sequential"],
        "repeated": [["order_id"]]
    },
    "olist_order_reviews_dataset": {
        "id": ["review_id"],
        "repeated": [["order_id"]]
    },
    "olist_orders_dataset": {
        "id": ["order_id"],
        "repeated": []
    },
    "olist_products_dataset": {
        "id": ["product_id"],
        "repeated": [["product_category_name"]]
    },
    "olist_sellers_dataset": {
        "id": ["seller_id"],
        "repeated": [["seller_zip_code_prefix"]]
    },
    "product_category_name_translation": {
        "id": ["product_category_name"],
        "repeated": []
    }
}

duplicate_rows = []
repeated_rows = []

for table_name, rules in key_rules.items():
    df = tables[table_name]
    keys_to_check = []

    if rules["id"] is not None:
        keys_to_check.append(("Định danh", rules["id"]))

    keys_to_check.extend(
        ("Lặp dự kiến", keys)
        for keys in rules["repeated"]
    )

    calculations = [
        df.map_partitions(len).sum(),
        df.drop_duplicates().map_partitions(len).sum()
    ]

    calculations.extend(
        df.dropna(subset=keys).groupby(keys).size()
        for _, keys in keys_to_check
    )

    results = dask.compute(*calculations)
    total_rows = int(results[0])
    distinct_rows = int(results[1])

    id_values = {
        "Khóa định danh": "Không có",
        "Nhóm khóa định danh trùng": None,
        "Dòng dư theo định danh": None
    }

    for (kind, keys), counts in zip(keys_to_check, results[2:]):
        repeated_groups = int((counts > 1).sum())
        extra_rows = int(counts.sum() - len(counts))

        if kind == "Định danh":
            id_values = {
                "Khóa định danh": " + ".join(keys),
                "Nhóm khóa định danh trùng": repeated_groups,
                "Dòng dư theo định danh": extra_rows
            }
        else:
            repeated_rows.append({
                "Bảng": table_name,
                "Khóa lặp theo quan hệ": " + ".join(keys),
                "Số khóa xuất hiện nhiều lần": repeated_groups,
                "Số dòng vượt quá một dòng mỗi khóa": extra_rows
            })

    duplicate_rows.append({
        "Bảng": table_name,
        "Số dòng": total_rows,
        "Dòng trùng hoàn toàn": total_rows - distinct_rows,
        **id_values
    })

duplicate_summary = pd.DataFrame(duplicate_rows)
repeated_summary = pd.DataFrame(repeated_rows)

table_css = ["""
:host .tabulator,
:host .tabulator * {
    color: #000000 !important;
    background-color: #ffffff !important;
}
"""]

display(
    pn.Column(
        pn.pane.Markdown(
            "### Dòng trùng hoàn toàn và khóa định danh trùng",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            duplicate_summary,
            show_index=False,
            theme="bootstrap5",
            width=1250,
            height=350,
            stylesheets=table_css
        ),
        pn.pane.Markdown(
            "### Khóa lặp theo quan hệ một–nhiều",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            repeated_summary,
            show_index=False,
            theme="bootstrap5",
            width=1250,
            height=400,
            stylesheets=table_css
        ),
        styles={"background": "#ffffff", "padding": "20px"}
    )
)

/tmp/ipykernel_2812/882350392.py:5: UserWarning: Using Panel interactively in Colab notebooks requires the jupyter_bokeh package to be installed. Install it with:

    !pip install jupyter_bokeh

and try again.
  pn.extension("tabulator")

Column(styles={'background': '#ffffff', ...})
    [0] Markdown(str, styles={'color': '#000000'})
    [1] Tabulator(height=350, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=              ..., width=1250)
    [2] Markdown(str, styles={'color': '#000000'})
    [3] Tabulator(height=400, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=              ..., width=1250)

### Cell code 06A: Trực quan hóa duplicate và khóa lặp

- **Mục đích:** Biểu diễn số dòng trùng hoàn toàn, dòng dư theo định danh và khóa lặp hợp lệ.
- **Vì sao:** Hai bảng thống kê ở Cell 06 chứa nhiều loại trùng lặp khác nhau.
- **Giúp ích:** Phân biệt nhanh duplicate thực sự với quan hệ một–nhiều hợp lệ.

In [24]:
dup_plot = duplicate_summary.copy()

dup_plot["Dòng trùng hoàn toàn"] = pd.to_numeric(
    dup_plot["Dòng trùng hoàn toàn"],
    errors="coerce"
).fillna(0)

dup_plot["Dòng dư theo định danh"] = pd.to_numeric(
    dup_plot["Dòng dư theo định danh"],
    errors="coerce"
).fillna(0)

dup_plot["Bảng"] = dup_plot["Bảng"].astype(str)

plot_full_duplicates = dup_plot.hvplot.bar(
    x="Bảng",
    y="Dòng trùng hoàn toàn",
    width=1100,
    height=430,
    rot=45,
    title="Số dòng trùng hoàn toàn theo từng bảng",
    xlabel="Bảng",
    ylabel="Số dòng trùng"
).opts(
    hooks=[black_chart_text]
)

display(plot_full_duplicates)

plot_id_duplicates = dup_plot.hvplot.bar(
    x="Bảng",
    y="Dòng dư theo định danh",
    width=1100,
    height=430,
    rot=45,
    title="Số dòng dư theo khóa định danh",
    xlabel="Bảng",
    ylabel="Số dòng dư"
).opts(
    hooks=[black_chart_text]
)

display(plot_id_duplicates)

repeat_plot = repeated_summary.copy()

repeat_plot["Số khóa xuất hiện nhiều lần"] = pd.to_numeric(
    repeat_plot["Số khóa xuất hiện nhiều lần"],
    errors="coerce"
).fillna(0)

repeat_plot["Quan hệ"] = (
    repeat_plot["Bảng"].astype(str)
    + " | "
    + repeat_plot["Khóa lặp theo quan hệ"].astype(str)
)

plot_repeated_keys = repeat_plot.hvplot.bar(
    x="Quan hệ",
    y="Số khóa xuất hiện nhiều lần",
    width=1200,
    height=460,
    rot=45,
    title="Số khóa xuất hiện nhiều lần theo quan hệ một-nhiều",
    xlabel="Quan hệ",
    ylabel="Số khóa"
).opts(
    hooks=[black_chart_text]
)

display(plot_repeated_keys)

:Bars   [Bảng]   (Dòng trùng hoàn toàn)

:Bars   [Bảng]   (Dòng dư theo định danh)

:Bars   [Quan hệ]   (Số khóa xuất hiện nhiều lần)

##Nhận xét:
- Qua thống kê, nhận thấy 8/9 bảng không có dòng trùng hoàn toàn và các khóa định danh được kiểm tra đều duy nhất, ngoại trừ bảng reviews: có 789 review_id xuất hiện nhiều lần, tạo 814 dòng vượt quá một dòng mỗi mã. Nhóm sẽ kiểm tra các review này trước khi quyết định xử lý vì chúng không phải dòng trùng hoàn toàn.
- Bảng geolocation có 261.831 dòng trùng hoàn toàn và không có khóa định danh duy nhất. Việc order_id lặp trong order_items, payments và reviews phản ánh quan hệ một–nhiều; nhóm sẽ tổng hợp các bảng này về cấp đơn hàng trước khi ghép để tránh nhân số dòng và tính sai đặc trưng.

##Kiểm tra bảng review

### Cell code 07: Xem review_id lặp

- **Mục đích:** Phân tích các review_id xuất hiện nhiều lần và các order_id liên kết.
- **Vì sao:** Không thể mặc định mỗi dòng là một lượt đánh giá mới.
- **Giúp ích:** Khoanh vùng các liên kết review cần kiểm tra sâu.

In [9]:
import pandas as pd
import panel as pn

pn.extension("tabulator")

reviews = tables["olist_order_reviews_dataset"]

review_counts = reviews.groupby("review_id").size().compute()
repeated_ids = review_counts[review_counts > 1].index.tolist()

repeated_reviews = reviews[
    reviews["review_id"].isin(repeated_ids)
].compute()

profile = repeated_reviews.groupby("review_id").agg(
    so_dong=("order_id", "size"),
    so_order_id=("order_id", lambda x: x.nunique(dropna=False))
)

distinct_rows = (
    repeated_reviews
    .drop_duplicates()
    .groupby("review_id")
    .size()
)

profile["so_ban_ghi_khac_nhau"] = distinct_rows
profile["dong_du"] = profile["so_dong"] - 1
profile["phan_loai"] = "Cùng order_id, dữ liệu khác"

profile.loc[
    profile["so_order_id"] > 1,
    "phan_loai"
] = "Gắn với nhiều order_id"

profile.loc[
    (profile["so_order_id"] == 1)
    & (profile["so_ban_ghi_khac_nhau"] == 1),
    "phan_loai"
] = "Trùng hoàn toàn"

profile = profile.reset_index().rename(columns={
    "review_id": "review_id",
    "so_dong": "Số dòng",
    "so_order_id": "Số order_id",
    "so_ban_ghi_khac_nhau": "Số bản ghi khác nhau",
    "dong_du": "Dòng dư",
    "phan_loai": "Phân loại"
})

case_summary = (
    profile.groupby("Phân loại", as_index=False)
    .agg(
        so_review_id=("review_id", "size"),
        tong_dong_du=("Dòng dư", "sum")
    )
    .rename(columns={
        "so_review_id": "Số review_id",
        "tong_dong_du": "Tổng dòng dư"
    })
)

size_summary = (
    profile.groupby(["Số dòng", "Phân loại"])
    .size()
    .reset_index(name="Số review_id")
    .sort_values(["Số dòng", "Phân loại"])
)

sample_ids = (
    profile.sort_values(["Phân loại", "Dòng dư"], ascending=[True, False])
    .groupby("Phân loại", group_keys=False)
    .head(3)["review_id"]
    .tolist()
)

sample_reviews = (
    repeated_reviews[
        repeated_reviews["review_id"].isin(sample_ids)
    ]
    .sort_values(["review_id", "order_id"])
    .reset_index(drop=True)
)

print(
    f"Review ID bị lặp: {len(profile):,} | "
    f"Dòng thuộc các ID bị lặp: {len(repeated_reviews):,} | "
    f"Dòng dư: {profile['Dòng dư'].sum():,}"
)

table_css = ["""
:host .tabulator,
:host .tabulator * {
    color: #000000 !important;
    background-color: #ffffff !important;
}
"""]

display(
    pn.Column(
        pn.pane.Markdown(
            "### Phân loại review_id bị lặp",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            case_summary,
            show_index=False,
            theme="bootstrap5",
            width=750,
            height=180,
            stylesheets=table_css
        ),
        pn.pane.Markdown(
            "### Mỗi review_id xuất hiện bao nhiêu dòng",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            size_summary,
            show_index=False,
            theme="bootstrap5",
            width=750,
            height=220,
            stylesheets=table_css
        ),
        pn.pane.Markdown(
            "### Chi tiết từng review_id bị lặp",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            profile.sort_values("Dòng dư", ascending=False),
            show_index=False,
            theme="bootstrap5",
            width=1150,
            height=350,
            pagination="local",
            page_size=15,
            stylesheets=table_css
        ),
        pn.pane.Markdown(
            "### Bản ghi gốc mẫu của từng loại",
            styles={"color": "#000000"}
        ),
        pn.widgets.Tabulator(
            sample_reviews,
            show_index=False,
            theme="bootstrap5",
            width=1500,
            height=350,
            pagination="local",
            page_size=15,
            stylesheets=table_css
        ),
        styles={"background": "#ffffff", "padding": "20px"}
    )
)

/tmp/ipykernel_2812/3744271458.py:4: UserWarning: Using Panel interactively in Colab notebooks requires the jupyter_bokeh package to be installed. Install it with:

    !pip install jupyter_bokeh

and try again.
  pn.extension("tabulator")

Review ID bị lặp: 789 | Dòng thuộc các ID bị lặp: 1,603 | Dòng dư: 814

Column(styles={'background': '#ffffff', ...})
    [0] Markdown(str, styles={'color': '#000000'})
    [1] Tabulator(height=180, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=              ..., width=750)
    [2] Markdown(str, styles={'color': '#000000'})
    [3] Tabulator(height=220, show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=   Số dòng    ..., width=750)
    [4] Markdown(str, styles={'color': '#000000'})
    [5] Tabulator(height=350, page_size=15, pagination='local', show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=              ..., width=1150)
    [6] Markdown(str, styles={'color': '#000000'})
    [7] Tabulator(height=350, page_size=15, pagination='local', show_index=False, sizing_mode='fixed', stylesheets=['\n:host .tabulator,\...], theme='bootstrap5', value=              ..., width=1500)

### Cell code 07A: Trực quan hóa review_id bị lặp

- **Mục đích:** Trực quan hóa loại review_id lặp và số lần mỗi review_id xuất hiện.
- **Vì sao:** `case_summary` và `size_summary` dễ đọc hơn khi chuyển thành biểu đồ.
- **Giúp ích:** Nhìn ngay mức độ lặp và cấu trúc các nhóm review bất thường.

In [10]:
# Cell code 07A: Trực quan hóa review_id bị lặp
import hvplot.pandas

review_type_plot = case_summary.hvplot.bar(
    x="Phân loại",
    y="Số review_id",
    width=900,
    height=400,
    rot=25,
    title="Phân loại các review_id bị lặp",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

size_plot = (
    size_summary.groupby("Số dòng", as_index=False)["Số review_id"]
    .sum()
    .sort_values("Số dòng")
)

review_size_plot = size_plot.hvplot.bar(
    x="Số dòng",
    y="Số review_id",
    width=850,
    height=400,
    title="Phân bố số lần xuất hiện của review_id bị lặp",
    xlabel="Số dòng / review_id",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

display(
    pn.Column(
        review_type_plot,
        review_size_plot,
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

Column(styles={'background': 'white', ...})
    [0] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=850)

##Nhận xét:
- Qua kiểm tra, có 789 review_id bị lặp đều gắn với nhiều order_id: 764 mã xuất hiện ở 2 đơn và 25 mã xuất hiện ở 3 đơn, tạo tổng cộng 814 dòng dư theo review_id. Không có dòng nào trùng hoàn toàn; các bản ghi mẫu có cùng nội dung đánh giá nhưng khác order_id.

##Kiểm tra: các đơn đó có thuộc cùng khách hàng không,

### Cell code 08: Đối chiếu khách của review lặp

- **Mục đích:** Nối reviews, orders và customers để xem các đơn cùng review_id thuộc khách nào.
- **Vì sao:** Cùng ID gắn với nhiều khách sẽ có ý nghĩa khác với nhiều đơn của một khách.
- **Giúp ích:** Làm rõ phạm vi bất thường ở cấp khách hàng.

In [11]:
from IPython.display import display

reviews = tables["olist_order_reviews_dataset"]
orders = tables["olist_orders_dataset"]
customers = tables["olist_customers_dataset"]

review_counts = reviews.groupby("review_id").size().compute()
repeated_ids = review_counts[review_counts > 1].index.tolist()

review_orders = (
    reviews[reviews["review_id"].isin(repeated_ids)]
    .merge(
        orders[
            ["order_id", "customer_id", "order_purchase_timestamp"]
        ],
        on="order_id",
        how="left"
    )
    .merge(
        customers[
            ["customer_id", "customer_unique_id"]
        ],
        on="customer_id",
        how="left"
    )
    .compute()
)

customer_check = (
    review_orders.groupby("review_id")
    .agg(
        so_dong=("order_id", "size"),
        so_order_id=("order_id", lambda x: x.nunique(dropna=True)),
        so_khach_hang=("customer_unique_id", lambda x: x.nunique(dropna=True)),
        don_khong_khop=("customer_id", lambda x: x.isna().sum()),
        khach_khong_khop=("customer_unique_id", lambda x: x.isna().sum())
    )
    .reset_index()
)

customer_check["ket_luan"] = "Cùng một khách hàng"

customer_check.loc[
    customer_check["so_khach_hang"] > 1,
    "ket_luan"
] = "Khác khách hàng"

customer_check.loc[
    (customer_check["don_khong_khop"] > 0)
    | (customer_check["khach_khong_khop"] > 0),
    "ket_luan"
] = "Chưa xác định do không khớp khóa"

summary = (
    customer_check.groupby("ket_luan", as_index=False)
    .agg(
        so_review_id=("review_id", "size"),
        so_order_id=("so_order_id", "sum")
    )
    .rename(columns={
        "ket_luan": "Kết luận",
        "so_review_id": "Số review_id",
        "so_order_id": "Tổng số đơn trong các nhóm"
    })
)

sample_ids = (
    customer_check
    .sort_values(["ket_luan", "so_dong"], ascending=[True, False])
    .groupby("ket_luan", group_keys=False)
    .head(3)["review_id"]
    .tolist()
)

sample_orders = (
    review_orders[
        review_orders["review_id"].isin(sample_ids)
    ][[
        "review_id",
        "order_id",
        "customer_id",
        "customer_unique_id",
        "order_purchase_timestamp",
        "review_score",
        "review_creation_date",
        "review_answer_timestamp"
    ]]
    .sort_values(["review_id", "order_purchase_timestamp"])
    .reset_index(drop=True)
)

print(f"Số review_id được kiểm tra: {len(customer_check):,}")

print("\nTổng hợp kết quả")
display(summary)

print("\nCác review_id gắn với nhiều khách hàng hoặc không khớp khóa")
display(
    customer_check[
        customer_check["ket_luan"] != "Cùng một khách hàng"
    ].head(30)
)

print("\nMẫu đơn hàng và khách hàng của từng nhóm")
display(sample_orders)

Số review_id được kiểm tra: 789

Tổng hợp kết quả

              Kết luận  Số review_id  Tổng số đơn trong các nhóm
0  Cùng một khách hàng           789                        1603

Các review_id gắn với nhiều khách hàng hoặc không khớp khóa

Empty DataFrame
Columns: [review_id, so_dong, so_order_id, so_khach_hang, don_khong_khop, khach_khong_khop, ket_luan]
Index: []

Mẫu đơn hàng và khách hàng của từng nhóm

,review_id,order_id,customer_id,customer_unique_id,order_purchase_timestamp,review_score,review_creation_date,review_answer_timestamp
0,08528f70f579f0c830189efc523d2182,53c71d3953507c6239ff73917ed358c9,26dcb450c4b5b390e79e6d5d0f2c6535,46450c74a0d8c5ca9395da1daac6c120,2018-07-24 20:41:01,1.0,2018-08-03 00:00:00,2018-08-06 00:09:52
1,08528f70f579f0c830189efc523d2182,03310aa823a66056268a3bab36e827fb,25dbbf0c477fd4ae0880aaffbb12e8b3,46450c74a0d8c5ca9395da1daac6c120,2018-08-07 16:33:59,1.0,2018-08-03 00:00:00,2018-08-06 00:09:52
2,08528f70f579f0c830189efc523d2182,7813842ae95e8c497fc0233232ae815a,040d94f8ba8ca26014bd6f7e8a6e0c0d,46450c74a0d8c5ca9395da1daac6c120,2018-08-17 20:06:36,1.0,2018-08-03 00:00:00,2018-08-06 00:09:52
3,0c76e7a547a531e7bf9f0b99cba071c1,98c977c116f7779360e9fecffd3860b6,e144d625b739ab69821471cc91327926,74cb1ad7e6d5674325c1f99b5ea30d82,2017-08-28 20:24:52,5.0,2017-08-31 00:00:00,2017-09-05 15:27:17
4,0c76e7a547a531e7bf9f0b99cba071c1,3525e0e57f9d276d522d570bd46cb39c,780a6f1f890da521b37306aa08a6c4ea,74cb1ad7e6d5674325c1f99b5ea30d82,2017-08-28 20:24:53,5.0,2017-08-31 00:00:00,2017-09-05 15:27:17
5,0c76e7a547a531e7bf9f0b99cba071c1,16cc0fe71527d13426bdbe29205b2053,806972b159c0b485d212c2c35012c012,74cb1ad7e6d5674325c1f99b5ea30d82,2017-08-28 20:24:53,5.0,2017-08-31 00:00:00,2017-09-05 15:27:17
6,1fb4ddc969e6bea80e38deec00393a6f,d6dde74bdeb424af6b660214881b4845,137da6b7c6f269c569e4377b37b84242,6a80a86f478a93a5f4c7ba8db6441a6b,2017-07-26 17:22:33,5.0,2017-08-11 00:00:00,2017-08-12 14:35:35
7,1fb4ddc969e6bea80e38deec00393a6f,afed4265a8b956d840bc032e54dfccd1,e08f49e30ad8f0c2a6db4d6fc316c841,6a80a86f478a93a5f4c7ba8db6441a6b,2017-07-26 17:22:34,5.0,2017-08-11 00:00:00,2017-08-12 14:35:35
8,1fb4ddc969e6bea80e38deec00393a6f,3c1098cb17277b62cfc709c7a9b500f5,1e041fde4b0aa2047b6b3d7f6cbf82fb,6a80a86f478a93a5f4c7ba8db6441a6b,2017-07-26 17:22:35,5.0,2017-08-11 00:00:00,2017-08-12 14:35:35

### Cell code 08A: Trực quan hóa quan hệ review_id và khách hàng

- **Mục đích:** Trực quan hóa review_id lặp thuộc cùng hay khác khách hàng và số đơn liên kết.
- **Vì sao:** Cell 08 chủ yếu xuất bảng đối chiếu theo `customer_unique_id`.
- **Giúp ích:** Kiểm tra nhanh xem review_id lặp có bị trộn giữa nhiều khách hàng hay không.

In [12]:
# Cell code 08A: Trực quan hóa quan hệ review_id và khách hàng
import hvplot.pandas

customer_result = (
    customer_check.groupby("ket_luan")
    .size()
    .reset_index(name="Số review_id")
    .rename(columns={"ket_luan": "Kết luận"})
)

customer_result_plot = customer_result.hvplot.bar(
    x="Kết luận",
    y="Số review_id",
    width=900,
    height=400,
    rot=20,
    title="Review_id lặp thuộc cùng hay khác khách hàng",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

order_distribution = (
    customer_check.groupby("so_order_id")
    .size()
    .reset_index(name="Số review_id")
    .rename(columns={"so_order_id": "Số order_id liên kết"})
    .sort_values("Số order_id liên kết")
)

order_distribution_plot = order_distribution.hvplot.bar(
    x="Số order_id liên kết",
    y="Số review_id",
    width=850,
    height=400,
    title="Số đơn liên kết với mỗi review_id bị lặp",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

display(
    pn.Column(
        customer_result_plot,
        order_distribution_plot,
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

Column(styles={'background': 'white', ...})
    [0] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=850)

##Nhận xét:
- Qua kiểm tra, có 789 review_id bị lặp đều gắn với các đơn của cùng một customer_unique_id; không có nhóm nào thuộc nhiều khách hàng hoặc bị thiếu khóa nối. Vì vậy, việc lặp mã review không làm lẫn đánh giá giữa các khách hàng.

### Cell code 09: Kiểm tra thời gian review và đặt đơn

- **Mục đích:** Dùng PySpark so ngày tạo/trả lời review với ngày mua trên các ID lặp.
- **Vì sao:** Đánh giá của một đơn không thể được tạo trước khi đơn đó được đặt.
- **Giúp ích:** Phát hiện liên kết review–đơn không hợp lý về thời gian.

In [13]:
%pip -q install pyspark

from pathlib import Path
from google.colab import drive
from pyspark.sql import SparkSession

data_dir = Path("/content/drive/MyDrive/BigData/DA-BigData/code/data")

if not data_dir.exists():
    drive.mount("/content/drive")

spark = SparkSession.builder.appName("OlistReviewTimeline").getOrCreate()

reviews = (
    spark.read.option("header", True)
    .option("multiLine", True)
    .option("escape", '"')
    .csv(str(data_dir / "olist_order_reviews_dataset.csv"))
)

orders = (
    spark.read.option("header", True)
    .csv(str(data_dir / "olist_orders_dataset.csv"))
)

reviews.createOrReplaceTempView("reviews")
orders.createOrReplaceTempView("orders")

review_timeline = spark.sql("""
    WITH repeated_ids AS (
        SELECT review_id
        FROM reviews
        WHERE review_id IS NOT NULL
        GROUP BY review_id
        HAVING COUNT(*) > 1
    ),
    linked AS (
        SELECT
            r.review_id,
            r.order_id,
            o.order_purchase_timestamp,
            r.review_creation_date,
            r.review_answer_timestamp,
            to_timestamp(o.order_purchase_timestamp) AS purchased_at,
            to_date(substr(r.review_creation_date, 1, 10)) AS created_on,
            to_timestamp(r.review_answer_timestamp) AS answered_at
        FROM reviews r
        JOIN repeated_ids d ON r.review_id = d.review_id
        LEFT JOIN orders o ON r.order_id = o.order_id
    )
    SELECT
        *,
        CASE WHEN created_on < to_date(purchased_at) THEN 1 ELSE 0 END AS created_before_purchase,
        CASE WHEN answered_at < purchased_at THEN 1 ELSE 0 END AS answered_before_purchase,
        CASE WHEN created_on = to_date(purchased_at) THEN 1 ELSE 0 END AS created_same_day_as_purchase
    FROM linked
""").cache()

review_timeline.createOrReplaceTempView("review_timeline")

print("THỐNG KÊ TOÀN BỘ NHÓM REVIEW_ID LẶP")
spark.sql("""
    SELECT
        COUNT(DISTINCT review_id) AS so_nhom_review_id_lap,
        COUNT(*) AS so_dong_lien_ket,
        SUM(created_before_purchase) AS so_dong_tao_truoc_ngay_mua,
        COUNT(DISTINCT CASE WHEN created_before_purchase = 1 THEN review_id END) AS so_nhom_tao_truoc_ngay_mua,
        SUM(answered_before_purchase) AS so_dong_tra_loi_truoc_luc_mua,
        COUNT(DISTINCT CASE WHEN answered_before_purchase = 1 THEN review_id END) AS so_nhom_tra_loi_truoc_luc_mua,
        SUM(created_same_day_as_purchase) AS so_dong_tao_cung_ngay_mua,
        SUM(CASE WHEN purchased_at IS NULL THEN 1 ELSE 0 END) AS so_dong_thieu_ngay_mua,
        SUM(CASE WHEN created_on IS NULL THEN 1 ELSE 0 END) AS so_dong_thieu_ngay_tao,
        SUM(CASE WHEN answered_at IS NULL THEN 1 ELSE 0 END) AS so_dong_thieu_luc_tra_loi
    FROM review_timeline
""").show(truncate=False)

print("CÁC DÒNG CÓ REVIEW ĐƯỢC TẠO HOẶC TRẢ LỜI TRƯỚC KHI MUA")
review_timeline.filter(
    "created_before_purchase = 1 OR answered_before_purchase = 1"
).select(
    "review_id",
    "order_id",
    "order_purchase_timestamp",
    "review_creation_date",
    "review_answer_timestamp",
    "created_before_purchase",
    "answered_before_purchase"
).orderBy(
    "review_id", "order_purchase_timestamp"
).show(review_timeline.count(), truncate=False)

THỐNG KÊ TOÀN BỘ NHÓM REVIEW_ID LẶP
+---------------------+----------------+--------------------------+--------------------------+-----------------------------+-----------------------------+-------------------------+----------------------+----------------------+-------------------------+
|so_nhom_review_id_lap|so_dong_lien_ket|so_dong_tao_truoc_ngay_mua|so_nhom_tao_truoc_ngay_mua|so_dong_tra_loi_truoc_luc_mua|so_nhom_tra_loi_truoc_luc_mua|so_dong_tao_cung_ngay_mua|so_dong_thieu_ngay_mua|so_dong_thieu_ngay_tao|so_dong_thieu_luc_tra_loi|
+---------------------+----------------+--------------------------+--------------------------+-----------------------------+-----------------------------+-------------------------+----------------------+----------------------+-------------------------+
|789                  |1603            |40                        |32                        |39                           |31                           |5                        |0                     |0                     |0                        |
+---------------------+----------------+--------------------------+--------------------------+-----------------------------+-----------------------------+-------------------------+----------------------+----------------------+-------------------------+

CÁC DÒNG CÓ REVIEW ĐƯỢC TẠO HOẶC TRẢ LỜI TRƯỚC KHI MUA
+--------------------------------+--------------------------------+------------------------+--------------------+-----------------------+-----------------------+------------------------+
|review_id                       |order_id                        |order_purchase_timestamp|review_creation_date|review_answer_timestamp|created_before_purchase|answered_before_purchase|
+--------------------------------+--------------------------------+------------------------+--------------------+-----------------------+-----------------------+------------------------+
|047fd109ced39e02296f6aeb74f6a6f1|236e6ec6171c1870d4bcf4ccfad87f49|2018-08-21 15:12:31     |2018-07-31 00:00:00 |2018-08-02 15:11:49    |1                      |1                       |
|047fd109ced39e02296f6aeb74f6a6f1|a89abace0dcc01eeb267a9660b5ac126|2018-09-06 18:45:47     |2018-07-31 00:00:00 |2018-08-02 15:11:49    |1                      |1                       |
|08528f70f579f0c830189efc523d2182|03310aa823a66056268a3bab36e827fb|2018-08-07 16:33:59     |2018-08-03 00:00:00 |2018-08-06 00:09:52    |1                      |1                       |
|08528f70f579f0c830189efc523d2182|7813842ae95e8c497fc0233232ae815a|2018-08-17 20:06:36     |2018-08-03 00:00:00 |2018-08-06 00:09:52    |1                      |1                       |
|1775bd097716d67420d128df008252eb|04a2ba381317648726f46210a46ece95|2018-08-09 09:13:44     |2018-08-04 00:00:00 |2018-08-04 21:58:02    |1                      |1                       |
|18071cb247f057c348988037fa94a0cd|4c8b9947280829d0a8b7e81cc249b875|2018-08-09 14:54:47     |2018-08-02 00:00:00 |2018-08-03 01:34:51    |1                      |1                       |
|18071cb247f057c348988037fa94a0cd|27667a063cb59b5d987a5a71c192cce5|2018-08-27 19:54:54     |2018-08-02 00:00:00 |2018-08-03 01:34:51    |1                      |1                       |
|19194f53840fc6c2857dd8809972a209|82fd1196a459f594fb1d66e667fc74c4|2018-04-10 21:09:18     |2018-01-23 00:00:00 |2018-01-24 12:43:58    |1                      |1                       |
|32415bbf6e341d5d517080a796f79b5c|1ad22e16129698e1a3cc11e4350d2cb7|2018-09-12 15:32:16     |2018-08-29 00:00:00 |2018-08-31 22:29:09    |1                      |1                       |
|32415bbf6e341d5d517080a796f79b5c|bd35b677fd239386e9861d11ae98ab56|2018-09-17 17:21:16     |2018-08-29 00:00:00 |2018-08-31 22:29:09    |1                      |1                       |
|3415c9f764e478409e8e0660ae816dd2|572c4bbf0f5f85a9b4a2c4fe0c7f04d5|2018-08-30 15:11:58     |2018-07-31 00:00:00 |2018-07-31 23:11:57    |1                      |1                       |
|3415c9f764e478409e8e0660ae816dd2|4d59cc2a2e7bb6c0a851725f5888a9b5|2018-09-06 14:50:07     |2018-07-31 00:00:00 |2018-07-31 23:11:57    |1                      |1                       |
|3a5a10d592a6e639cdb9330c9e6d2a87|5290c34bd38a8a095b885f13958db1e1|2018-08-21 10:25:18     |2018-08-18 00:00:00 |2018-08-21 00:47:13    |1                      |1                       |
|4548534449b1f572e357211b90724f1b|cfdfd7862e532c4ec1ed1c6a1b56d320|2018-09-03 18:45:34     |2018-08-18 00:00:00 |2018-08-19 00:39:54    |1                      |1                       |
|4548534449b1f572e357211b90724f1b|a2ac6dad85cf8af5b0afb510a240fe8c|2018-10-03 18:55:29     |2018-08-18 00:00:00 |2018-08-19 00:39:54    |1                      |1                       |
|48198628b2d43ed394089750acc59c3f|b059ee4de278302d550a3035c4cdb740|2018-10-16 20:16:02     |2018-06-27 00:00:00 |2018-06-30 01:48:53    |1                      |1                       |
|56647f8fbe7430f42719c0510d99e636|21a00b08cbeb5716bbb66105e3dbd850|2018-09-10 17:51:25     |2018-08-25 00:00:00 |2018-08-27 14:39:04    |1                      |1                       |
|58f1655df206a9a40482b929b81ee671|f81e71dd7c044a9ee7c1d6e37d68d64f|2018-08-15 08:34:42     |2018-07-21 00:00:00 |2018-07-24 00:09:40    |1                      |1                       |
|63c51abb0488ed1346fe3215f1571f15|756fc608f67478946b31c752681f27be|2018-08-14 08:14:45     |2018-07-28 00:00:00 |2018-07-30 11:53:34    |1                      |1                       |
|68a97595d96f3890eb24bd5bd2654339|0a472c47d928bf4cd8b6a7a30345eeb7|2018-08-30 10:14:00     |2018-08-28 00:00:00 |2018-08-30 11:14:50    |1                      |0                       |
|6e4344680dbd30c75f78394e0dcfffdf|ed3efbd3a87bea76c2812c66a0b32219|2018-09-20 13:54:16     |2018-07-28 00:00:00 |2018-07-30 11:06:16    |1                      |1                       |
|6efce984242ca6456d74750810733a03|54282e97f61c23b78330c15b154c867d|2018-09-03 09:06:57     |2018-08-31 00:00:00 |2018-08-31 09:51:47    |1                      |1                       |
|778826f9af6467ff6268bbcf436cd3c5|450c49623c365a4edcf0c5a2c93aa7c9|2017-03-01 08:08:10     |2017-02-22 00:00:00 |2017-02-22 14:05:09    |1                      |1                       |
|8a90511249a72061a421c9bbb7a6f45f|a805d7a514bcde0719f99ddf2a3bb31d|2018-08-17 14:17:56     |2018-07-14 00:00:00 |2018-07-18 19:09:23    |1                      |1                       |
|8b8f495d30fca09fdc8312e96de1bc47|616fa7d4871b87832197b2a137a115d2|2018-10-01 15:30:09     |2018-08-23 00:00:00 |2018-08-23 23:14:33    |1                      |1                       |
|9e25d6e3025e9b9a0fc7f03588d33e2b|0d3adebce4bebc1f80a7f36e9833f497|2018-09-03 18:40:50     |2018-08-31 00:00:00 |2018-09-03 09:33:00    |1                      |1                       |
|9e25d6e3025e9b9a0fc7f03588d33e2b|869997fbe01f39d184956b5c6bccfdbe|2018-09-26 08:40:15     |2018-08-31 00:00:00 |2018-09-03 09:33:00    |1                      |1                       |
|a05a89a9daa1ef53175c02ff565ce0b5|c306eca42d32507b970739b5b6a5a33a|2018-08-13 09:14:07     |2018-08-08 00:00:00 |2018-08-10 11:39:37    |1                      |1                       |
|a169c853a5ba10abfccb9c9afb06aa60|af07804a2d53e8639954baf97fbf803a|2018-04-19 13:46:42     |2018-03-10 00:00:00 |2018-03-11 00:15:42    |1                      |1                       |
|a935b3d67f406bac4853776d80a05220|4a62fb19d5fa08fb514619dfcc617b3d|2018-05-09 19:23:46     |2018-05-05 00:00:00 |2018-05-08 02:06:50    |1                      |1                       |
|abbfacb2964f74f6487c9c10ac46daa6|81b7c7bbc8ec003eeb67d87441a6a148|2018-08-20 09:03:23     |2018-08-15 00:00:00 |2018-08-19 22:35:54    |1                      |1                       |
|abbfacb2964f74f6487c9c10ac46daa6|47282cfe5747c1c19920f090e491d285|2018-08-23 12:38:08     |2018-08-15 00:00:00 |2018-08-19 22:35:54    |1                      |1                       |
|b370661a9286b652f0ee547c13cb03d1|d2bc174d5c413f457a21db6899afb682|2018-08-09 09:50:42     |2018-08-05 00:00:00 |2018-08-07 20:08:40    |1                      |1                       |
|b54d02f7f1520b3995f84b77ab0dacb3|c8c528189310eaa44a745b8d9d26908b|2018-08-28 20:05:14     |2018-08-24 00:00:00 |2018-08-25 02:24:54    |1                      |1                       |
|d25026282e14fc531f0711246e121cc2|ebc94658c583ab37ad4f8e9091c4bef2|2018-04-14 08:22:43     |2018-03-30 00:00:00 |2018-04-02 00:32:35    |1                      |1                       |
|da8e936bc2f1b52ec626f8aa41f3df44|0fb9645c128ac84788798f0129496ca7|2018-08-21 10:15:51     |2018-08-04 00:00:00 |2018-08-05 17:21:32    |1                      |1                       |
|e5b48a584cec8406e2722967491b4627|bb8edfe0742a6a0279b7dff848289568|2018-08-30 10:24:34     |2018-08-26 00:00:00 |2018-08-26 23:39:07    |1                      |1                       |
|e6acae33a98861be63cf635525330891|5aac76cf7b07dd06fa4d50bf461d2f40|2018-09-25 11:59:18     |2018-08-14 00:00:00 |2018-08-28 15:02:02    |1                      |1                       |
|f45e3373e177f56944a549ff601f838b|2663ce3526465b7ee9809428adabdc45|2018-08-30 13:07:46     |2018-08-23 00:00:00 |2018-08-24 00:31:45    |1                      |1                       |
|fbb7c6f69326ad5bf986c099bedefdb4|4608a27e9e60c05b054631def491e7af|2018-08-28 08:10:22     |2018-08-08 00:00:00 |2018-08-10 13:14:46    |1                      |1                       |
+--------------------------------+--------------------------------+------------------------+--------------------+-----------------------+-----------------------+------------------------+

### Cell code 09A: Trực quan hóa bất thường thời gian review

- **Mục đích:** Chuyển thống kê Spark về các mốc review–mua hàng thành biểu đồ.
- **Vì sao:** Output `.show()` của Spark khó so sánh trực quan giữa nhiều loại bất thường.
- **Giúp ích:** Nhìn nhanh số dòng và số nhóm review có mốc thời gian bất hợp lý.

In [25]:
timeline_stats = spark.sql("""
    SELECT
        SUM(created_before_purchase) AS dong_review_tao_truoc_mua,

        COUNT(
            DISTINCT CASE
                WHEN created_before_purchase = 1
                THEN review_id
            END
        ) AS nhom_review_tao_truoc_mua,

        SUM(answered_before_purchase) AS dong_review_tra_loi_truoc_mua,

        COUNT(
            DISTINCT CASE
                WHEN answered_before_purchase = 1
                THEN review_id
            END
        ) AS nhom_review_tra_loi_truoc_mua,

        SUM(created_same_day_as_purchase) AS dong_review_cung_ngay_mua

    FROM review_timeline
""").toPandas()

timeline_plot = timeline_stats.T.reset_index()

timeline_plot.columns = [
    "Loại kiểm tra",
    "Số lượng"
]

timeline_plot["Loại kiểm tra"] = (
    timeline_plot["Loại kiểm tra"]
    .astype(str)
    .replace({
        "dong_review_tao_truoc_mua":
            "Dòng review tạo trước ngày mua",

        "nhom_review_tao_truoc_mua":
            "Nhóm review tạo trước ngày mua",

        "dong_review_tra_loi_truoc_mua":
            "Dòng trả lời trước lúc mua",

        "nhom_review_tra_loi_truoc_mua":
            "Nhóm trả lời trước lúc mua",

        "dong_review_cung_ngay_mua":
            "Review tạo cùng ngày mua"
    })
)

timeline_plot["Số lượng"] = pd.to_numeric(
    timeline_plot["Số lượng"],
    errors="coerce"
).fillna(0).astype(float)

plot_timeline = timeline_plot.hvplot.bar(
    x="Loại kiểm tra",
    y="Số lượng",
    width=1100,
    height=450,
    rot=35,
    title="Các bất thường về thời gian của review_id bị lặp",
    xlabel="Loại kiểm tra",
    ylabel="Số lượng"
).opts(
    hooks=[black_chart_text]
)

display(plot_timeline)

:Bars   [Loại kiểm tra]   (Số lượng)

##Nhận xét:
- Trong 789 review_id bị lặp (1.603 dòng liên kết), có 40 dòng thuộc 32 nhóm mà ngày tạo review sớm hơn ngày mua đơn liên kết; 39 dòng thuộc 31 nhóm có thời điểm trả lời sớm hơn lúc mua. Bởi vì hai nhóm số liệu này có thể trùng nhau nên không cộng lại. Không có giá trị thời gian bị thiếu.

##Kiểm tra cả 789 nhóm review lặp: với mỗi đơn liên kết, đối chiếu ngày mua, ngày giao hàng và ngày tạo review; đồng thời kiểm tra review_score có thiếu hoặc khác nhau trong cùng review_id.

### Cell code 10: Kiểm toán toàn bộ nhóm review lặp

- **Mục đích:** So ngày mua, ngày giao, ngày review và điểm số trong từng nhóm.
- **Vì sao:** Một liên kết đúng ngày mua vẫn có thể có vấn đề về giao hàng hoặc điểm số.
- **Giúp ích:** Biết nhóm nào cần xem xét trước khi dùng review làm feature.

In [15]:
from pyspark.sql import functions as F

review_audit = spark.sql("""
    WITH repeated_ids AS (
        SELECT review_id
        FROM reviews
        WHERE review_id IS NOT NULL
        GROUP BY review_id
        HAVING COUNT(*) > 1
    ),
    linked AS (
        SELECT
            r.review_id,
            r.order_id,
            r.review_score,
            o.order_status,
            o.order_purchase_timestamp,
            o.order_delivered_customer_date,
            r.review_creation_date,
            r.review_answer_timestamp,
            to_timestamp(o.order_purchase_timestamp) AS purchased_at,
            to_timestamp(o.order_delivered_customer_date) AS delivered_at,
            to_date(substr(r.review_creation_date, 1, 10)) AS review_on
        FROM reviews r
        JOIN repeated_ids d ON r.review_id = d.review_id
        LEFT JOIN orders o ON r.order_id = o.order_id
    )
    SELECT
        *,
        CASE WHEN review_on < to_date(purchased_at) THEN 1 ELSE 0 END AS review_before_purchase,
        CASE WHEN delivered_at < purchased_at THEN 1 ELSE 0 END AS delivered_before_purchase,
        CASE WHEN review_on < to_date(delivered_at) THEN 1 ELSE 0 END AS review_before_delivery,
        CASE WHEN order_status = 'delivered' AND delivered_at IS NULL THEN 1 ELSE 0 END AS delivered_order_missing_date,
        CASE WHEN review_score IS NULL OR trim(review_score) = '' THEN 1 ELSE 0 END AS missing_score,
        CASE WHEN review_score IS NOT NULL
                  AND trim(review_score) <> ''
                  AND trim(review_score) NOT RLIKE '^[1-5]$'
             THEN 1 ELSE 0 END AS invalid_score
    FROM linked
""").cache()

review_audit.createOrReplaceTempView("review_audit")

group_audit = spark.sql("""
    SELECT
        review_id,
        COUNT(*) AS so_dong,
        COUNT(DISTINCT order_id) AS so_don,
        COUNT(DISTINCT trim(review_score)) AS so_diem_khac_nhau,
        SUM(missing_score) AS so_dong_thieu_diem,
        SUM(invalid_score) AS so_dong_diem_ngoai_1_5,
        SUM(review_before_purchase) AS so_dong_review_truoc_mua,
        SUM(delivered_before_purchase) AS so_dong_giao_truoc_mua,
        SUM(review_before_delivery) AS so_dong_review_truoc_giao,
        SUM(delivered_order_missing_date) AS so_don_da_giao_thieu_ngay_giao
    FROM review_audit
    GROUP BY review_id
""").cache()

group_audit.createOrReplaceTempView("group_audit")

print("THỐNG KÊ CHO TOÀN BỘ NHÓM REVIEW_ID LẶP")
spark.sql("""
    SELECT
        COUNT(*) AS so_nhom,
        SUM(so_dong) AS so_dong_lien_ket,
        SUM(CASE WHEN so_diem_khac_nhau > 1 THEN 1 ELSE 0 END) AS nhom_co_diem_khac_nhau,
        SUM(CASE WHEN so_dong_thieu_diem > 0 THEN 1 ELSE 0 END) AS nhom_thieu_diem,
        SUM(CASE WHEN so_dong_diem_ngoai_1_5 > 0 THEN 1 ELSE 0 END) AS nhom_diem_ngoai_1_5,
        SUM(CASE WHEN so_dong_review_truoc_mua > 0 THEN 1 ELSE 0 END) AS nhom_review_truoc_mua,
        SUM(CASE WHEN so_dong_giao_truoc_mua > 0 THEN 1 ELSE 0 END) AS nhom_giao_truoc_mua,
        SUM(CASE WHEN so_dong_review_truoc_giao > 0 THEN 1 ELSE 0 END) AS nhom_review_truoc_giao,
        SUM(CASE WHEN so_don_da_giao_thieu_ngay_giao > 0 THEN 1 ELSE 0 END) AS nhom_da_giao_thieu_ngay_giao
    FROM group_audit
""").show(truncate=False)

print("KẾT QUẢ TỪNG NHÓM")
group_audit.orderBy("review_id").show(group_audit.count(), truncate=False)

print("MẪU ĐƠN LIÊN KẾT CẦN XEM XÉT")
review_audit.filter(
    (F.col("review_before_purchase") == 1) |
    (F.col("delivered_before_purchase") == 1) |
    (F.col("review_before_delivery") == 1) |
    (F.col("delivered_order_missing_date") == 1) |
    (F.col("missing_score") == 1) |
    (F.col("invalid_score") == 1)
).select(
    "review_id",
    "order_id",
    "review_score",
    "order_status",
    "order_purchase_timestamp",
    "order_delivered_customer_date",
    "review_creation_date",
    "review_before_purchase",
    "delivered_before_purchase",
    "review_before_delivery"
).orderBy("review_id", "order_purchase_timestamp").show(review_audit.count(), truncate=False)

THỐNG KÊ CHO TOÀN BỘ NHÓM REVIEW_ID LẶP
+-------+----------------+----------------------+---------------+-------------------+---------------------+-------------------+----------------------+----------------------------+
|so_nhom|so_dong_lien_ket|nhom_co_diem_khac_nhau|nhom_thieu_diem|nhom_diem_ngoai_1_5|nhom_review_truoc_mua|nhom_giao_truoc_mua|nhom_review_truoc_giao|nhom_da_giao_thieu_ngay_giao|
+-------+----------------+----------------------+---------------+-------------------+---------------------+-------------------+----------------------+----------------------------+
|789    |1603            |0                     |0              |0                  |32                   |0                  |267                   |0                           |
+-------+----------------+----------------------+---------------+-------------------+---------------------+-------------------+----------------------+----------------------------+

KẾT QUẢ TỪNG NHÓM
+--------------------------------+-------+------+-----------------+------------------+----------------------+------------------------+----------------------+-------------------------+------------------------------+
|review_id                       |so_dong|so_don|so_diem_khac_nhau|so_dong_thieu_diem|so_dong_diem_ngoai_1_5|so_dong_review_truoc_mua|so_dong_giao_truoc_mua|so_dong_review_truoc_giao|so_don_da_giao_thieu_ngay_giao|
+--------------------------------+-------+------+-----------------+------------------+----------------------+------------------------+----------------------+-------------------------+------------------------------+
|00130cbe1f9d422698c812ed8ded1919|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0115633a9c298b6a98bcbe4eee75345f|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0174caf0ee5964646040cd94e15ac95e|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|017808d29fd1f942d97e50184dfb4c13|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0254bd905dc677a6078990aad3331a36|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0288d42bef3dfe36930740c9588a570f|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|02aa7f5f75e964e3c7efa59a1f515281|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|034528cb00b6bc981847acafbdf2ae0b|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|03a6a25db577d0689440933055111897|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0467560f511c516ddaa54a60edb0c291|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|047fd109ced39e02296f6aeb74f6a6f1|2      |2     |1                |0                 |0                     |2                       |0                     |0                        |0                             |
|0498e9722f8757426c3c3ee0b91e666d|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0501aab2f381486c36bf0f071442c0c2|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0546d398a833d4c33dec480bedeecfbd|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0655af56f10bc3ef8e3810610828f294|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|06e327fb381850fdd69fba40ad61b2f2|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0837bc8fa2cb75353513858b3bb5be1d|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|08528f70f579f0c830189efc523d2182|3      |3     |1                |0                 |0                     |2                       |0                     |0                        |0                             |
|08531aa0b3844944e7aeef53530f8598|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|08a86da22498172adb6cefaa99fdfaf7|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|090aa2980b0aea78cd1ae73447d7d55b|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|09534ea272eea99209ff37c5c348ceb1|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|09b871b3f4f85d3595cb37054a9105f1|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0a2d1206f8b2473cd3ddf69b51bca98a|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0a3b875d00f437f25215e0ac942efca2|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0a3caf6324edd5158b342ee5a0886271|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0a6ec47c5d78509672e16b95efcff53b|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0ad57b9e68d4d34814464772b6de54fe|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0ad87184dc47c36db717b98e8baca9cc|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0b51553f3cd2e9606b9c0f25667dc5bb|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0b9af3c12843b743f612ca8abbc33e83|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0bb958acd9e40d9348635c75013f7b19|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0c0b58839bdc7b7d49396ddf94a3dbf7|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0c1f10775ef729e60b56d9c6dcc47736|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0c2915e69ee09c18b9c15b8035bdc5ff|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0c76e7a547a531e7bf9f0b99cba071c1|3      |3     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0c8e7347f1cdd2aede37371543e3d163|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0e18d426420da859dfd6fb4beaba9efe|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0e249472bec47b0c4b88a8e8bfa8d241|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0ec0f24aa34a9b25fb0f7b32034965ce|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0efebc2c5add22c5b45867716919dcdd|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|0f45a7a6cab5ac1c9cc25ce1eb2357d2|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|0ffae99e57188428340c206afb957a1c|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|10398bad17ab17c451c39a0b2c47464c|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|105facb42b5b9147996f0b1b6fbf7b80|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|10bca0461c36ef14701fa28971d0cdb5|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|11912dbae5f169782098a20fc51c0b33|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|11c94569cabc7d493a0aa1c5cd1dbfb4|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|12476f0c366e9de86c46fbced6372d92|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1258a603cc9e4897f7955ab218c83b8c|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|12f2fd663de5670387805fd70ece2e21|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|135df63f4871bf893d89ca67df0f921c|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|13b2872ada20991c4f52ccb141cb1705|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|13cc14a5f7a442a1ecce8f32b463e242|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|13d45c97ae78e0ef1361835b8944b7b0|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1439640ba4905dc2f98188cad2a77154|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1442a23fe4555fda0f7c7eb7ba5ae3b1|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|15c9136f43468a8428316d9871eaf14d|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|15daa9db89623052d7b25d96ed14686d|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|161160f7f3602ec0de9cd583b62b3b15|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|167b40b617e650de2c473d70baae2e65|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|168b708c0e1d90f89c9737b1160121d6|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1708c3eec64152cb52fe56bb3abcf257|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|17592266cd3216a98665ebfd6365843a|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|176a37898b45f9db0b8de7641973bf53|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1775bd097716d67420d128df008252eb|2      |2     |1                |0                 |0                     |1                       |0                     |0                        |0                             |
|17939259ccc419f355fb4a148151fb00|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|18071cb247f057c348988037fa94a0cd|2      |2     |1                |0                 |0                     |2                       |0                     |0                        |0                             |
|183808dc516fab3df74b087310299cf0|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|19194f53840fc6c2857dd8809972a209|2      |2     |1                |0                 |0                     |1                       |0                     |1                        |0                             |
|193d73d33b656807084215db91b23b8c|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1961cafe1d1cbd4cc701c2f0160467ff|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|19d60869413aa63834affc9ecc9d9f90|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1a6be4c794d5e3da242a364f6a98163f|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1b5dc3da2372e9bb5518cd37cd9a9354|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1b8df55d40e129a4003858afb671129c|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1bda8c20e199f7c2e9a342600031518b|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1c0c84f0e3132c3af0a17f0aa4987879|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1c7a92108afc9782646581517fbb2808|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1c7b8b15de9a2eff8caac4ece3fc0f49|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1c7e1a24358cea9db1eecc6987843a28|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1c9023a88f4effba4abbf114c58bedba|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1ce9388b1a3ad76f5f1a64f208a90fce|2      |2     |1                |0                 |0                     |0                       |0                     |1                        |0                             |
|1d5b8cc3cac5888ebfc80a0dcd337f07|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |
|1dee9d450a2b8533d2085cef898ca4a2|2      |2     |1                |0                 |0                     |0                       |0                     |0                        |0                             |

### Cell code 10A: Trực quan hóa kết quả kiểm toán review

- **Mục đích:** Tổng hợp các loại vấn đề chất lượng của 789 nhóm review_id lặp thành biểu đồ.
- **Vì sao:** Cell 10 chứa nhiều chỉ tiêu kiểm toán ở cả cấp nhóm và cấp đơn.
- **Giúp ích:** Nhận diện nhanh loại vấn đề xuất hiện nhiều nhất trước khi quyết định cách xử lý.

In [26]:
audit_summary_plot = spark.sql("""
    SELECT
        SUM(
            CASE WHEN so_diem_khac_nhau > 1
            THEN 1 ELSE 0 END
        ) AS diem_khac_nhau,

        SUM(
            CASE WHEN so_dong_thieu_diem > 0
            THEN 1 ELSE 0 END
        ) AS thieu_diem,

        SUM(
            CASE WHEN so_dong_diem_ngoai_1_5 > 0
            THEN 1 ELSE 0 END
        ) AS diem_ngoai_1_5,

        SUM(
            CASE WHEN so_dong_review_truoc_mua > 0
            THEN 1 ELSE 0 END
        ) AS review_truoc_mua,

        SUM(
            CASE WHEN so_dong_giao_truoc_mua > 0
            THEN 1 ELSE 0 END
        ) AS giao_truoc_mua,

        SUM(
            CASE WHEN so_dong_review_truoc_giao > 0
            THEN 1 ELSE 0 END
        ) AS review_truoc_giao,

        SUM(
            CASE WHEN so_don_da_giao_thieu_ngay_giao > 0
            THEN 1 ELSE 0 END
        ) AS da_giao_thieu_ngay_giao

    FROM group_audit
""").toPandas()

audit_plot = audit_summary_plot.T.reset_index()

audit_plot.columns = [
    "Loại vấn đề",
    "Số nhóm review_id"
]

audit_plot["Loại vấn đề"] = (
    audit_plot["Loại vấn đề"]
    .astype(str)
    .replace({
        "diem_khac_nhau": "Điểm khác nhau",
        "thieu_diem": "Thiếu điểm",
        "diem_ngoai_1_5": "Điểm ngoài 1–5",
        "review_truoc_mua": "Review trước mua",
        "giao_truoc_mua": "Giao trước mua",
        "review_truoc_giao": "Review trước giao",
        "da_giao_thieu_ngay_giao":
            "Đã giao nhưng thiếu ngày giao"
    })
)

audit_plot["Số nhóm review_id"] = pd.to_numeric(
    audit_plot["Số nhóm review_id"],
    errors="coerce"
).fillna(0).astype(float)

plot_audit = audit_plot.hvplot.bar(
    x="Loại vấn đề",
    y="Số nhóm review_id",
    width=1100,
    height=450,
    rot=35,
    title="Kết quả kiểm toán 789 nhóm review_id bị lặp",
    xlabel="Loại vấn đề",
    ylabel="Số nhóm review_id"
).opts(
    hooks=[black_chart_text]
)

display(plot_audit)

:Bars   [Loại vấn đề]   (Số nhóm review_id)

##Nhận xét:
- Trong 789 nhóm review_id lặp (1.603 dòng), điểm đánh giá của mỗi nhóm đều thống nhất, không thiếu và đều nằm trong khoảng 1–5. Không có trường hợp ghi nhận giao hàng trước khi mua.
- Có 32 nhóm gắn review với đơn mua sau ngày tạo review. Ngoài ra, 267 nhóm có ít nhất một đơn mà review được tạo trước ngày giao hàng; điều này chưa đủ để kết luận dữ liệu sai, vì khách có thể đánh giá khi hàng đang giao hoặc đơn giao trễ.

##Kiểm tra các đơn trong 32 nhóm: đơn nào mua trước hoặc sau ngày tạo review, trạng thái từng đơn và ngày giao hàng.

### Cell code 11: Xem chi tiết 32 nhóm review bất thường

- **Mục đích:** Hiển thị tất cả đơn của các nhóm có review tạo trước ngày mua.
- **Vì sao:** Cần nhìn cả đơn mua trước và mua sau để hiểu một review_id bị gắn thế nào.
- **Giúp ích:** Hỗ trợ phân loại liên kết rõ ràng và liên kết chưa xác định.

In [17]:
review_32 = spark.sql("""
    SELECT
        a.review_id,
        a.order_id,
        a.review_score,
        a.review_creation_date,
        a.review_answer_timestamp,
        a.order_purchase_timestamp,
        a.order_status,
        a.order_delivered_customer_date,
        CASE
            WHEN to_date(a.purchased_at) < a.review_on THEN 'Mua trước review'
            WHEN to_date(a.purchased_at) = a.review_on THEN 'Mua cùng ngày review'
            WHEN to_date(a.purchased_at) > a.review_on THEN 'Mua sau review'
            ELSE 'Thiếu ngày mua'
        END AS thu_tu_mua_review,
        a.review_before_delivery
    FROM review_audit a
    JOIN group_audit g ON a.review_id = g.review_id
    WHERE g.so_dong_review_truoc_mua > 0
""").cache()

review_32.createOrReplaceTempView("review_32")

print("TỔNG HỢP 32 NHÓM")
spark.sql("""
    SELECT
        review_id,
        COUNT(*) AS so_don_lien_ket,
        SUM(CASE WHEN thu_tu_mua_review = 'Mua trước review' THEN 1 ELSE 0 END) AS so_don_mua_truoc_review,
        SUM(CASE WHEN thu_tu_mua_review = 'Mua cùng ngày review' THEN 1 ELSE 0 END) AS so_don_mua_cung_ngay,
        SUM(CASE WHEN thu_tu_mua_review = 'Mua sau review' THEN 1 ELSE 0 END) AS so_don_mua_sau_review,
        SUM(CASE WHEN order_status = 'delivered' THEN 1 ELSE 0 END) AS so_don_da_giao,
        SUM(CASE WHEN order_status = 'canceled' THEN 1 ELSE 0 END) AS so_don_da_huy,
        SUM(review_before_delivery) AS so_don_review_truoc_giao
    FROM review_32
    GROUP BY review_id
    ORDER BY review_id
""").show(32, truncate=False)

print("CHI TIẾT TẤT CẢ ĐƠN TRONG 32 NHÓM")
review_32.orderBy(
    "review_id", "order_purchase_timestamp"
).show(review_32.count(), truncate=False)

TỔNG HỢP 32 NHÓM
+--------------------------------+---------------+-----------------------+--------------------+---------------------+--------------+-------------+------------------------+
|review_id                       |so_don_lien_ket|so_don_mua_truoc_review|so_don_mua_cung_ngay|so_don_mua_sau_review|so_don_da_giao|so_don_da_huy|so_don_review_truoc_giao|
+--------------------------------+---------------+-----------------------+--------------------+---------------------+--------------+-------------+------------------------+
|047fd109ced39e02296f6aeb74f6a6f1|2              |0                      |0                   |2                    |0             |2            |0                       |
|08528f70f579f0c830189efc523d2182|3              |1                      |0                   |2                    |1             |2            |0                       |
|1775bd097716d67420d128df008252eb|2              |1                      |0                   |1                    |1             |1            |0                       |
|18071cb247f057c348988037fa94a0cd|2              |0                      |0                   |2                    |0             |2            |0                       |
|19194f53840fc6c2857dd8809972a209|2              |1                      |0                   |1                    |2             |0            |1                       |
|32415bbf6e341d5d517080a796f79b5c|3              |0                      |1                   |2                    |0             |3            |0                       |
|3415c9f764e478409e8e0660ae816dd2|3              |1                      |0                   |2                    |1             |2            |0                       |
|3a5a10d592a6e639cdb9330c9e6d2a87|2              |1                      |0                   |1                    |1             |1            |0                       |
|4548534449b1f572e357211b90724f1b|3              |1                      |0                   |2                    |1             |2            |0                       |
|48198628b2d43ed394089750acc59c3f|2              |1                      |0                   |1                    |1             |1            |0                       |
|56647f8fbe7430f42719c0510d99e636|2              |1                      |0                   |1                    |1             |1            |0                       |
|58f1655df206a9a40482b929b81ee671|2              |1                      |0                   |1                    |1             |1            |0                       |
|63c51abb0488ed1346fe3215f1571f15|2              |1                      |0                   |1                    |1             |1            |0                       |
|68a97595d96f3890eb24bd5bd2654339|2              |1                      |0                   |1                    |1             |1            |0                       |
|6e4344680dbd30c75f78394e0dcfffdf|2              |1                      |0                   |1                    |1             |1            |0                       |
|6efce984242ca6456d74750810733a03|2              |1                      |0                   |1                    |0             |0            |0                       |
|778826f9af6467ff6268bbcf436cd3c5|2              |1                      |0                   |1                    |2             |0            |1                       |
|8a90511249a72061a421c9bbb7a6f45f|2              |1                      |0                   |1                    |1             |1            |0                       |
|8b8f495d30fca09fdc8312e96de1bc47|2              |1                      |0                   |1                    |1             |1            |0                       |
|9e25d6e3025e9b9a0fc7f03588d33e2b|3              |1                      |0                   |2                    |1             |2            |0                       |
|a05a89a9daa1ef53175c02ff565ce0b5|2              |1                      |0                   |1                    |1             |1            |0                       |
|a169c853a5ba10abfccb9c9afb06aa60|2              |1                      |0                   |1                    |1             |1            |0                       |
|a935b3d67f406bac4853776d80a05220|2              |1                      |0                   |1                    |2             |0            |1                       |
|abbfacb2964f74f6487c9c10ac46daa6|3              |1                      |0                   |2                    |0             |2            |0                       |
|b370661a9286b652f0ee547c13cb03d1|2              |1                      |0                   |1                    |1             |1            |0                       |
|b54d02f7f1520b3995f84b77ab0dacb3|2              |1                      |0                   |1                    |1             |1            |0                       |
|d25026282e14fc531f0711246e121cc2|2              |1                      |0                   |1                    |2             |0            |1                       |
|da8e936bc2f1b52ec626f8aa41f3df44|2              |1                      |0                   |1                    |1             |1            |0                       |
|e5b48a584cec8406e2722967491b4627|2              |1                      |0                   |1                    |0             |1            |0                       |
|e6acae33a98861be63cf635525330891|2              |1                      |0                   |1                    |1             |1            |0                       |
|f45e3373e177f56944a549ff601f838b|2              |1                      |0                   |1                    |1             |1            |0                       |
|fbb7c6f69326ad5bf986c099bedefdb4|2              |1                      |0                   |1                    |1             |1            |0                       |
+--------------------------------+---------------+-----------------------+--------------------+---------------------+--------------+-------------+------------------------+

CHI TIẾT TẤT CẢ ĐƠN TRONG 32 NHÓM
+--------------------------------+--------------------------------+------------+--------------------+-----------------------+------------------------+------------+-----------------------------+--------------------+----------------------+
|review_id                       |order_id                        |review_score|review_creation_date|review_answer_timestamp|order_purchase_timestamp|order_status|order_delivered_customer_date|thu_tu_mua_review   |review_before_delivery|
+--------------------------------+--------------------------------+------------+--------------------+-----------------------+------------------------+------------+-----------------------------+--------------------+----------------------+
|047fd109ced39e02296f6aeb74f6a6f1|236e6ec6171c1870d4bcf4ccfad87f49|4           |2018-07-31 00:00:00 |2018-08-02 15:11:49    |2018-08-21 15:12:31     |canceled    |NULL                         |Mua sau review      |0                     |
|047fd109ced39e02296f6aeb74f6a6f1|a89abace0dcc01eeb267a9660b5ac126|4           |2018-07-31 00:00:00 |2018-08-02 15:11:49    |2018-09-06 18:45:47     |canceled    |NULL                         |Mua sau review      |0                     |
|08528f70f579f0c830189efc523d2182|53c71d3953507c6239ff73917ed358c9|1           |2018-08-03 00:00:00 |2018-08-06 00:09:52    |2018-07-24 20:41:01     |delivered   |2018-08-02 18:41:16          |Mua trước review    |0                     |
|08528f70f579f0c830189efc523d2182|03310aa823a66056268a3bab36e827fb|1           |2018-08-03 00:00:00 |2018-08-06 00:09:52    |2018-08-07 16:33:59     |canceled    |NULL                         |Mua sau review      |0                     |
|08528f70f579f0c830189efc523d2182|7813842ae95e8c497fc0233232ae815a|1           |2018-08-03 00:00:00 |2018-08-06 00:09:52    |2018-08-17 20:06:36     |canceled    |NULL                         |Mua sau review      |0                     |
|1775bd097716d67420d128df008252eb|0b3ca8c9e3b3199306adb467fcd0e982|5           |2018-08-04 00:00:00 |2018-08-04 21:58:02    |2018-07-16 13:34:31     |delivered   |2018-08-03 18:29:09          |Mua trước review    |0                     |
|1775bd097716d67420d128df008252eb|04a2ba381317648726f46210a46ece95|5           |2018-08-04 00:00:00 |2018-08-04 21:58:02    |2018-08-09 09:13:44     |canceled    |NULL                         |Mua sau review      |0                     |
|18071cb247f057c348988037fa94a0cd|4c8b9947280829d0a8b7e81cc249b875|1           |2018-08-02 00:00:00 |2018-08-03 01:34:51    |2018-08-09 14:54:47     |canceled    |NULL                         |Mua sau review      |0                     |
|18071cb247f057c348988037fa94a0cd|27667a063cb59b5d987a5a71c192cce5|1           |2018-08-02 00:00:00 |2018-08-03 01:34:51    |2018-08-27 19:54:54     |canceled    |NULL                         |Mua sau review      |0                     |
|19194f53840fc6c2857dd8809972a209|ca263afd88a8a1200605adbd4b63cd7d|4           |2018-01-23 00:00:00 |2018-01-24 12:43:58    |2018-01-12 18:17:53     |delivered   |2018-01-22 18:33:16          |Mua trước review    |0                     |
|19194f53840fc6c2857dd8809972a209|82fd1196a459f594fb1d66e667fc74c4|4           |2018-01-23 00:00:00 |2018-01-24 12:43:58    |2018-04-10 21:09:18     |delivered   |2018-04-21 00:51:34          |Mua sau review      |1                     |
|32415bbf6e341d5d517080a796f79b5c|65fdcb432cb9cfa970e3a3817b39040d|2           |2018-08-29 00:00:00 |2018-08-31 22:29:09    |2018-08-29 08:44:38     |canceled    |NULL                         |Mua cùng ngày review|0                     |
|32415bbf6e341d5d517080a796f79b5c|1ad22e16129698e1a3cc11e4350d2cb7|2           |2018-08-29 00:00:00 |2018-08-31 22:29:09    |2018-09-12 15:32:16     |canceled    |NULL                         |Mua sau review      |0                     |
|32415bbf6e341d5d517080a796f79b5c|bd35b677fd239386e9861d11ae98ab56|2           |2018-08-29 00:00:00 |2018-08-31 22:29:09    |2018-09-17 17:21:16     |canceled    |NULL                         |Mua sau review      |0                     |
|3415c9f764e478409e8e0660ae816dd2|4d808ed2901ed7dfebbb74bf1cbb74f6|5           |2018-07-31 00:00:00 |2018-07-31 23:11:57    |2018-07-26 10:19:28     |delivered   |2018-07-30 19:32:32          |Mua trước review    |0                     |
|3415c9f764e478409e8e0660ae816dd2|572c4bbf0f5f85a9b4a2c4fe0c7f04d5|5           |2018-07-31 00:00:00 |2018-07-31 23:11:57    |2018-08-30 15:11:58     |canceled    |NULL                         |Mua sau review      |0                     |
|3415c9f764e478409e8e0660ae816dd2|4d59cc2a2e7bb6c0a851725f5888a9b5|5           |2018-07-31 00:00:00 |2018-07-31 23:11:57    |2018-09-06 14:50:07     |canceled    |NULL                         |Mua sau review      |0                     |
|3a5a10d592a6e639cdb9330c9e6d2a87|9b8ac5a3f09f1af11380aa4451dc2ac4|3           |2018-08-18 00:00:00 |2018-08-21 00:47:13    |2018-08-08 15:40:33     |delivered   |2018-08-17 19:56:47          |Mua trước review    |0                     |
|3a5a10d592a6e639cdb9330c9e6d2a87|5290c34bd38a8a095b885f13958db1e1|3           |2018-08-18 00:00:00 |2018-08-21 00:47:13    |2018-08-21 10:25:18     |canceled    |NULL                         |Mua sau review      |0                     |
|4548534449b1f572e357211b90724f1b|73a8ed1078e1d475d2b1fb7216a52e1a|1           |2018-08-18 00:00:00 |2018-08-19 00:39:54    |2018-08-10 10:39:43     |delivered   |2018-08-17 21:21:58          |Mua trước review    |0                     |
|4548534449b1f572e357211b90724f1b|cfdfd7862e532c4ec1ed1c6a1b56d320|1           |2018-08-18 00:00:00 |2018-08-19 00:39:54    |2018-09-03 18:45:34     |canceled    |NULL                         |Mua sau review      |0                     |
|4548534449b1f572e357211b90724f1b|a2ac6dad85cf8af5b0afb510a240fe8c|1           |2018-08-18 00:00:00 |2018-08-19 00:39:54    |2018-10-03 18:55:29     |canceled    |NULL                         |Mua sau review      |0                     |
|48198628b2d43ed394089750acc59c3f|0f2335c85eae6c232fa46499d5e1e3d2|5           |2018-06-27 00:00:00 |2018-06-30 01:48:53    |2018-06-11 16:51:47     |delivered   |2018-06-26 20:03:32          |Mua trước review    |0                     |
|48198628b2d43ed394089750acc59c3f|b059ee4de278302d550a3035c4cdb740|5           |2018-06-27 00:00:00 |2018-06-30 01:48:53    |2018-10-16 20:16:02     |canceled    |NULL                         |Mua sau review      |0                     |
|56647f8fbe7430f42719c0510d99e636|9e119efc7690fb6c238eca967793fd34|1           |2018-08-25 00:00:00 |2018-08-27 14:39:04    |2018-08-18 15:26:01     |delivered   |2018-08-24 18:48:40          |Mua trước review    |0                     |
|56647f8fbe7430f42719c0510d99e636|21a00b08cbeb5716bbb66105e3dbd850|1           |2018-08-25 00:00:00 |2018-08-27 14:39:04    |2018-09-10 17:51:25     |canceled    |NULL                         |Mua sau review      |0                     |
|58f1655df206a9a40482b929b81ee671|67be6410d453784501c125d4f0ecb741|1           |2018-07-21 00:00:00 |2018-07-24 00:09:40    |2018-07-14 18:19:56     |delivered   |2018-07-20 20:21:55          |Mua trước review    |0                     |
|58f1655df206a9a40482b929b81ee671|f81e71dd7c044a9ee7c1d6e37d68d64f|1           |2018-07-21 00:00:00 |2018-07-24 00:09:40    |2018-08-15 08:34:42     |canceled    |NULL                         |Mua sau review      |0                     |
|63c51abb0488ed1346fe3215f1571f15|177200d363504ea94b5064b05929e2e6|1           |2018-07-28 00:00:00 |2018-07-30 11:53:34    |2018-07-19 16:22:41     |delivered   |2018-07-27 17:15:46          |Mua trước review    |0                     |
|63c51abb0488ed1346fe3215f1571f15|756fc608f67478946b31c752681f27be|1           |2018-07-28 00:00:00 |2018-07-30 11:53:34    |2018-08-14 08:14:45     |canceled    |NULL                         |Mua sau review      |0                     |
|68a97595d96f3890eb24bd5bd2654339|2bf9fdd42a3609f2c440bec186b10ff7|3           |2018-08-28 00:00:00 |2018-08-30 11:14:50    |2018-08-21 14:30:46     |delivered   |2018-08-27 17:22:45          |Mua trước review    |0                     |
|68a97595d96f3890eb24bd5bd2654339|0a472c47d928bf4cd8b6a7a30345eeb7|3           |2018-08-28 00:00:00 |2018-08-30 11:14:50    |2018-08-30 10:14:00     |canceled    |NULL                         |Mua sau review      |0                     |
|6e4344680dbd30c75f78394e0dcfffdf|4c888e6e352d77cd1e8beea1f03985b7|2           |2018-07-28 00:00:00 |2018-07-30 11:06:16    |2018-07-22 07:46:57     |delivered   |2018-07-27 20:16:44          |Mua trước review    |0                     |
|6e4344680dbd30c75f78394e0dcfffdf|ed3efbd3a87bea76c2812c66a0b32219|2           |2018-07-28 00:00:00 |2018-07-30 11:06:16    |2018-09-20 13:54:16     |canceled    |NULL                         |Mua sau review      |0                     |
|6efce984242ca6456d74750810733a03|6ca46f2b9a1592929647682510800e0e|1           |2018-08-31 00:00:00 |2018-08-31 09:51:47    |2018-08-24 17:02:19     |shipped     |NULL                         |Mua trước review    |0                     |
|6efce984242ca6456d74750810733a03|54282e97f61c23b78330c15b154c867d|1           |2018-08-31 00:00:00 |2018-08-31 09:51:47    |2018-09-03 09:06:57     |shipped     |NULL                         |Mua sau review      |0                     |
|778826f9af6467ff6268bbcf436cd3c5|b58c726e8f5ba3196c593b1837d25744|1           |2017-02-22 00:00:00 |2017-02-22 14:05:09    |2017-02-13 15:54:42     |delivered   |2017-02-20 16:27:40          |Mua trước review    |0                     |
|778826f9af6467ff6268bbcf436cd3c5|450c49623c365a4edcf0c5a2c93aa7c9|1           |2017-02-22 00:00:00 |2017-02-22 14:05:09    |2017-03-01 08:08:10     |delivered   |2017-03-08 10:26:04          |Mua sau review      |1                     |
|8a90511249a72061a421c9bbb7a6f45f|9c9c501f71dcf81d14d006826972733a|1           |2018-07-14 00:00:00 |2018-07-18 19:09:23    |2018-06-29 11:43:13     |delivered   |2018-07-13 13:06:53          |Mua trước review    |0                     |
|8a90511249a72061a421c9bbb7a6f45f|a805d7a514bcde0719f99ddf2a3bb31d|1           |2018-07-14 00:00:00 |2018-07-18 19:09:23    |2018-08-17 14:17:56     |canceled    |NULL                         |Mua sau review      |0                     |
|8b8f495d30fca09fdc8312e96de1bc47|b115422b830bf2840fccf6f0d6678ab2|2           |2018-08-23 00:00:00 |2018-08-23 23:14:33    |2018-08-16 13:09:43     |delivered   |2018-08-22 19:20:40          |Mua trước review    |0                     |
|8b8f495d30fca09fdc8312e96de1bc47|616fa7d4871b87832197b2a137a115d2|2           |2018-08-23 00:00:00 |2018-08-23 23:14:33    |2018-10-01 15:30:09     |canceled    |NULL                         |Mua sau review      |0                     |
|9e25d6e3025e9b9a0fc7f03588d33e2b|52b7fa35b1e5c8bdea5869804dced415|1           |2018-08-31 00:00:00 |2018-09-03 09:33:00    |2018-08-26 16:26:52     |delivered   |2018-08-30 21:05:53          |Mua trước review    |0                     |
|9e25d6e3025e9b9a0fc7f03588d33e2b|0d3adebce4bebc1f80a7f36e9833f497|1           |2018-08-31 00:00:00 |2018-09-03 09:33:00    |2018-09-03 18:40:50     |canceled    |NULL                         |Mua sau review      |0                     |
|9e25d6e3025e9b9a0fc7f03588d33e2b|869997fbe01f39d184956b5c6bccfdbe|1           |2018-08-31 00:00:00 |2018-09-03 09:33:00    |2018-09-26 08:40:15     |canceled    |NULL                         |Mua sau review      |0                     |
|a05a89a9daa1ef53175c02ff565ce0b5|bb874c45df1a3c97842d52f31efee99a|4           |2018-08-08 00:00:00 |2018-08-10 11:39:37    |2018-07-28 00:23:49     |delivered   |2018-08-07 19:28:41          |Mua trước review    |0                     |
|a05a89a9daa1ef53175c02ff565ce0b5|c306eca42d32507b970739b5b6a5a33a|4           |2018-08-08 00:00:00 |2018-08-10 11:39:37    |2018-08-13 09:14:07     |canceled    |NULL                         |Mua sau review      |0                     |
|a169c853a5ba10abfccb9c9afb06aa60|a3ef589d94a7dd3b117dc0e46c29d479|1           |2018-03-10 00:00:00 |2018-03-11 00:15:42    |2018-03-07 10:27:14     |delivered   |2018-03-09 19:40:38          |Mua trước review    |0                     |
|a169c853a5ba10abfccb9c9afb06aa60|af07804a2d53e8639954baf97fbf803a|1           |2018-03-10 00:00:00 |2018-03-11 00:15:42    |2018-04-19 13:46:42     |canceled    |NULL                         |Mua sau review      |0                     |
|a935b3d67f406bac4853776d80a05220|9db5ceb6f107ae0944c19188c8869a03|3           |2018-05-05 00:00:00 |2018-05-08 02:06:50    |2018-04-29 23:57:11     |delivered   |2018-05-04 22:31:59          |Mua trước review    |0                     |
|a935b3d67f406bac4853776d80a05220|4a62fb19d5fa08fb514619dfcc617b3d|3           |2018-05-05 00:00:00 |2018-05-08 02:06:50    |2018-05-09 19:23:46     |delivered   |2018-05-15 18:12:35          |Mua sau review      |1                     |
|abbfacb2964f74f6487c9c10ac46daa6|b02682757340133856bfb99145dd61cd|3           |2018-08-15 00:00:00 |2018-08-19 22:35:54    |2018-07-28 15:49:27     |shipped     |NULL                         |Mua trước review    |0                     |
|abbfacb2964f74f6487c9c10ac46daa6|81b7c7bbc8ec003eeb67d87441a6a148|3           |2018-08-15 00:00:00 |2018-08-19 22:35:54    |2018-08-20 09:03:23     |canceled    |NULL                         |Mua sau review      |0                     |
|abbfacb2964f74f6487c9c10ac46daa6|47282cfe5747c1c19920f090e491d285|3           |2018-08-15 00:00:00 |2018-08-19 22:35:54    |2018-08-23 12:38:08     |canceled    |NULL                         |Mua sau review      |0                     |

### Cell code 11A: Trực quan hóa 32 nhóm review bất thường

- **Mục đích:** Trực quan hóa thứ tự mua–review và trạng thái đơn trong 32 nhóm bất thường.
- **Vì sao:** Bảng chi tiết của Cell 11 rất dài và khó nhận ra phân bố tổng thể.
- **Giúp ích:** Thấy ngay bao nhiêu đơn mua trước/sau review và trạng thái của các đơn liên quan.

In [18]:
# Cell code 11A: Trực quan hóa 32 nhóm review bất thường
import hvplot.pandas

review_order_timing = (
    review_32.groupBy("thu_tu_mua_review")
    .count()
    .toPandas()
    .rename(columns={"thu_tu_mua_review": "Quan hệ thời gian", "count": "Số đơn"})
    .sort_values("Số đơn", ascending=False)
)

review_order_timing_plot = review_order_timing.hvplot.bar(
    x="Quan hệ thời gian",
    y="Số đơn",
    width=900,
    height=400,
    rot=20,
    title="Thứ tự mua hàng và thời điểm tạo review trong 32 nhóm",
    ylabel="Số đơn"
).opts(hooks=[black_chart_text])

status_32 = (
    review_32.groupBy("order_status")
    .count()
    .toPandas()
    .rename(columns={"order_status": "Trạng thái đơn", "count": "Số đơn"})
    .sort_values("Số đơn", ascending=False)
)

status_32_plot = status_32.hvplot.bar(
    x="Trạng thái đơn",
    y="Số đơn",
    width=900,
    height=400,
    rot=25,
    title="Trạng thái đơn hàng trong 32 nhóm review bất thường",
    ylabel="Số đơn"
).opts(hooks=[black_chart_text])

display(
    pn.Column(
        review_order_timing_plot,
        status_32_plot,
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

Column(styles={'background': 'white', ...})
    [0] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)

##Nhận xét:
- Có 29/32 nhóm có một đơn mua trước ngày tạo review và đơn khác mua sau đó. 2 nhóm chỉ liên kết với các đơn mua sau review; 1 nhóm có đơn mua cùng ngày nên chưa xác định được thứ tự chính xác.
- Có 40 đơn mua sau ngày tạo review. Phần lớn là đơn đã hủy, nhưng bảng chi tiết cũng có đơn đã giao, đang vận chuyển.

##Thống kê từng khách hàng theo id và liên kết qua lịch sử mua hàng của tưng khách hàng đó nhóm theo đơn hàng từ đó sau đó từ những đơn hàng đó thống kê có bao nhiêu review id

### Cell code 12: Theo dõi lịch sử mua của khách có review lặp

- **Mục đích:** Liệt kê đơn và review_id theo trình tự mua của từng khách liên quan.
- **Vì sao:** Lịch sử của khách giúp đối chiếu review với các đơn khác cùng người.
- **Giúp ích:** Thấy các trường hợp ID cũ xuất hiện lại ở đơn mua sau.

In [19]:
from pathlib import Path

customer_path = Path(data_dir) / "olist_customers_dataset.csv"

if not customer_path.exists():
    customer_path = next(
        Path("/content/drive").rglob("olist_customers_dataset.csv")
    )

customers = (
    spark.read.option("header", True)
    .csv(str(customer_path))
)

customers.createOrReplaceTempView("customers")

customer_order_history = spark.sql("""
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        o.order_status,
        o.order_delivered_customer_date,
        COUNT(r.review_id) AS so_dong_review,
        COUNT(DISTINCT r.review_id) AS so_review_id_cua_don,
        sort_array(collect_set(r.review_id)) AS danh_sach_review_id,
        MIN(r.review_creation_date) AS review_tao_som_nhat,
        MAX(r.review_creation_date) AS review_tao_muon_nhat
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    LEFT JOIN reviews r ON o.order_id = r.order_id
    GROUP BY
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        o.order_status,
        o.order_delivered_customer_date
""").cache()

customer_order_history.createOrReplaceTempView("customer_order_history")

customer_review_summary = spark.sql("""
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS tong_so_don,
        COUNT(r.review_id) AS tong_so_dong_review,
        COUNT(DISTINCT r.review_id) AS so_review_id_khac_nhau,
        COUNT(r.review_id) - COUNT(DISTINCT r.review_id) AS so_luot_review_id_lap
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    LEFT JOIN reviews r ON o.order_id = r.order_id
    GROUP BY c.customer_unique_id
""").cache()

customer_review_summary.createOrReplaceTempView("customer_review_summary")

target_customers = spark.sql("""
    SELECT
        c.customer_unique_id,
        sort_array(collect_set(x.review_id)) AS review_id_thuoc_32_nhom
    FROM review_32 x
    JOIN orders o ON x.order_id = o.order_id
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
""").cache()

target_customers.createOrReplaceTempView("target_customers")

print("QUY MÔ THỐNG KÊ TOÀN BỘ KHÁCH HÀNG")
spark.sql("""
    SELECT
        COUNT(*) AS so_khach_hang,
        SUM(tong_so_don) AS tong_so_don,
        SUM(tong_so_dong_review) AS tong_so_dong_review,
        SUM(so_luot_review_id_lap) AS tong_luot_review_id_lap_trong_tung_khach
    FROM customer_review_summary
""").show(truncate=False)

print("THỐNG KÊ KHÁCH HÀNG THUỘC 32 NHÓM")
target_summary = (
    customer_review_summary
    .join(target_customers, "customer_unique_id")
    .orderBy("customer_unique_id")
)

target_summary.show(target_summary.count(), truncate=False)

print("TOÀN BỘ LỊCH SỬ ĐƠN HÀNG CỦA NHỮNG KHÁCH NÀY")
target_history = (
    customer_order_history
    .join(target_customers, "customer_unique_id")
    .orderBy("customer_unique_id", "order_purchase_timestamp", "order_id")
)

target_history.show(target_history.count(), truncate=False)

QUY MÔ THỐNG KÊ TOÀN BỘ KHÁCH HÀNG
+-------------+-----------+-------------------+----------------------------------------+
|so_khach_hang|tong_so_don|tong_so_dong_review|tong_luot_review_id_lap_trong_tung_khach|
+-------------+-----------+-------------------+----------------------------------------+
|96096        |99441      |99224              |814                                     |
+-------------+-----------+-------------------+----------------------------------------+

THỐNG KÊ KHÁCH HÀNG THUỘC 32 NHÓM
+--------------------------------+-----------+-------------------+----------------------+---------------------+----------------------------------+
|customer_unique_id              |tong_so_don|tong_so_dong_review|so_review_id_khac_nhau|so_luot_review_id_lap|review_id_thuoc_32_nhom           |
+--------------------------------+-----------+-------------------+----------------------+---------------------+----------------------------------+
|00172711b30d52eea8b313a7f2cced02|2          |2                  |1                     |1                    |[a05a89a9daa1ef53175c02ff565ce0b5]|
|08642cd329066fe11ec63293f714f2f8|2          |2                  |1                     |1                    |[6e4344680dbd30c75f78394e0dcfffdf]|
|08f334e84bc7ab7b588cb7fc77dd7f4a|2          |2                  |1                     |1                    |[58f1655df206a9a40482b929b81ee671]|
|176c21456fab655afee57b3ea9799f47|2          |2                  |1                     |1                    |[da8e936bc2f1b52ec626f8aa41f3df44]|
|230a1e9f42924d41f37fd22a1d4a9707|3          |3                  |1                     |2                    |[3415c9f764e478409e8e0660ae816dd2]|
|262e1f1e26e92e86375f86840b4ffd63|2          |2                  |1                     |1                    |[48198628b2d43ed394089750acc59c3f]|
|3158fc4f60ca92412de397461b64cee3|2          |2                  |1                     |1                    |[68a97595d96f3890eb24bd5bd2654339]|
|391d6062da3dd65b4de4524f28c478de|2          |2                  |1                     |1                    |[18071cb247f057c348988037fa94a0cd]|
|46450c74a0d8c5ca9395da1daac6c120|3          |3                  |1                     |2                    |[08528f70f579f0c830189efc523d2182]|
|4e1554d1a2dcb38dcf22770eb7390fe1|2          |2                  |1                     |1                    |[fbb7c6f69326ad5bf986c099bedefdb4]|
|50c7adf7c25188cf27f66e1cfe278fad|2          |2                  |1                     |1                    |[b370661a9286b652f0ee547c13cb03d1]|
|5c96017028584678dd28c139566b87c0|2          |2                  |1                     |1                    |[d25026282e14fc531f0711246e121cc2]|
|634420a0ea42302205032ed44ac7fccc|2          |2                  |1                     |1                    |[8b8f495d30fca09fdc8312e96de1bc47]|
|6ba987d564bad1f9da8e14b9d3b71c8f|2          |2                  |1                     |1                    |[b54d02f7f1520b3995f84b77ab0dacb3]|
|6bb7c9ac69dc13b436f413acec41a1b6|2          |2                  |1                     |1                    |[63c51abb0488ed1346fe3215f1571f15]|
|76e5f3bca2b1f5c510c41563c2ea31a4|2          |2                  |1                     |1                    |[56647f8fbe7430f42719c0510d99e636]|
|8fe6fc853d687dac18df5b163f84d438|2          |2                  |1                     |1                    |[8a90511249a72061a421c9bbb7a6f45f]|
|91544d22848a922381b73b5e21ad58ff|2          |2                  |1                     |1                    |[e5b48a584cec8406e2722967491b4627]|
|9c3af16efacb7aa06aa3bc674556c5d6|2          |2                  |1                     |1                    |[e6acae33a98861be63cf635525330891]|
|af5454198a97379394cacf676e1e96cb|3          |3                  |1                     |2                    |[4548534449b1f572e357211b90724f1b]|
|b14ef688a7c1a52e7437298085d9d62b|2          |2                  |1                     |1                    |[a169c853a5ba10abfccb9c9afb06aa60]|
|ba84da8c159659f116329563a0a981dd|3          |3                  |1                     |2                    |[9e25d6e3025e9b9a0fc7f03588d33e2b]|
|c0394cfa96258a94e368499f919a3ba6|2          |4                  |2                     |2                    |[19194f53840fc6c2857dd8809972a209]|
|d05c44a138277ad325d915c6b7ccbcdf|2          |2                  |1                     |1                    |[047fd109ced39e02296f6aeb74f6a6f1]|
|d526c2df957cc6b177070216427c299d|2          |2                  |1                     |1                    |[1775bd097716d67420d128df008252eb]|
|e23daf58ce481f3d38066e654ef610cb|2          |3                  |2                     |1                    |[778826f9af6467ff6268bbcf436cd3c5]|
|e271fa40aa8fea4e0f304b3768b65d6a|2          |3                  |2                     |1                    |[a935b3d67f406bac4853776d80a05220]|
|e61f0f032bc92cadf0ec55f9c1c8b5ec|2          |2                  |1                     |1                    |[3a5a10d592a6e639cdb9330c9e6d2a87]|
|eb240714223915add224beff2d844e53|2          |2                  |1                     |1                    |[f45e3373e177f56944a549ff601f838b]|
|ef0103e9602d12594d19c2b666219bc1|3          |3                  |1                     |2                    |[32415bbf6e341d5d517080a796f79b5c]|
|ff22e30958c13ffe219db7d711e8f564|2          |2                  |1                     |1                    |[6efce984242ca6456d74750810733a03]|
|ff36be26206fffe1eb37afd54c70e18b|3          |3                  |1                     |2                    |[abbfacb2964f74f6487c9c10ac46daa6]|
+--------------------------------+-----------+-------------------+----------------------+---------------------+----------------------------------+

TOÀN BỘ LỊCH SỬ ĐƠN HÀNG CỦA NHỮNG KHÁCH NÀY
+--------------------------------+--------------------------------+------------------------+------------+-----------------------------+--------------+--------------------+--------------------------------------------------------------------+-------------------+--------------------+----------------------------------+
|customer_unique_id              |order_id                        |order_purchase_timestamp|order_status|order_delivered_customer_date|so_dong_review|so_review_id_cua_don|danh_sach_review_id                                                 |review_tao_som_nhat|review_tao_muon_nhat|review_id_thuoc_32_nhom           |
+--------------------------------+--------------------------------+------------------------+------------+-----------------------------+--------------+--------------------+--------------------------------------------------------------------+-------------------+--------------------+----------------------------------+
|00172711b30d52eea8b313a7f2cced02|bb874c45df1a3c97842d52f31efee99a|2018-07-28 00:23:49     |delivered   |2018-08-07 19:28:41          |1             |1                   |[a05a89a9daa1ef53175c02ff565ce0b5]                                  |2018-08-08 00:00:00|2018-08-08 00:00:00 |[a05a89a9daa1ef53175c02ff565ce0b5]|
|00172711b30d52eea8b313a7f2cced02|c306eca42d32507b970739b5b6a5a33a|2018-08-13 09:14:07     |canceled    |NULL                         |1             |1                   |[a05a89a9daa1ef53175c02ff565ce0b5]                                  |2018-08-08 00:00:00|2018-08-08 00:00:00 |[a05a89a9daa1ef53175c02ff565ce0b5]|
|08642cd329066fe11ec63293f714f2f8|4c888e6e352d77cd1e8beea1f03985b7|2018-07-22 07:46:57     |delivered   |2018-07-27 20:16:44          |1             |1                   |[6e4344680dbd30c75f78394e0dcfffdf]                                  |2018-07-28 00:00:00|2018-07-28 00:00:00 |[6e4344680dbd30c75f78394e0dcfffdf]|
|08642cd329066fe11ec63293f714f2f8|ed3efbd3a87bea76c2812c66a0b32219|2018-09-20 13:54:16     |canceled    |NULL                         |1             |1                   |[6e4344680dbd30c75f78394e0dcfffdf]                                  |2018-07-28 00:00:00|2018-07-28 00:00:00 |[6e4344680dbd30c75f78394e0dcfffdf]|
|08f334e84bc7ab7b588cb7fc77dd7f4a|67be6410d453784501c125d4f0ecb741|2018-07-14 18:19:56     |delivered   |2018-07-20 20:21:55          |1             |1                   |[58f1655df206a9a40482b929b81ee671]                                  |2018-07-21 00:00:00|2018-07-21 00:00:00 |[58f1655df206a9a40482b929b81ee671]|
|08f334e84bc7ab7b588cb7fc77dd7f4a|f81e71dd7c044a9ee7c1d6e37d68d64f|2018-08-15 08:34:42     |canceled    |NULL                         |1             |1                   |[58f1655df206a9a40482b929b81ee671]                                  |2018-07-21 00:00:00|2018-07-21 00:00:00 |[58f1655df206a9a40482b929b81ee671]|
|176c21456fab655afee57b3ea9799f47|117a6f28c5cf04526b4869a9291c9d61|2018-07-26 12:10:27     |delivered   |2018-08-03 18:59:02          |1             |1                   |[da8e936bc2f1b52ec626f8aa41f3df44]                                  |2018-08-04 00:00:00|2018-08-04 00:00:00 |[da8e936bc2f1b52ec626f8aa41f3df44]|
|176c21456fab655afee57b3ea9799f47|0fb9645c128ac84788798f0129496ca7|2018-08-21 10:15:51     |canceled    |NULL                         |1             |1                   |[da8e936bc2f1b52ec626f8aa41f3df44]                                  |2018-08-04 00:00:00|2018-08-04 00:00:00 |[da8e936bc2f1b52ec626f8aa41f3df44]|
|230a1e9f42924d41f37fd22a1d4a9707|4d808ed2901ed7dfebbb74bf1cbb74f6|2018-07-26 10:19:28     |delivered   |2018-07-30 19:32:32          |1             |1                   |[3415c9f764e478409e8e0660ae816dd2]                                  |2018-07-31 00:00:00|2018-07-31 00:00:00 |[3415c9f764e478409e8e0660ae816dd2]|
|230a1e9f42924d41f37fd22a1d4a9707|572c4bbf0f5f85a9b4a2c4fe0c7f04d5|2018-08-30 15:11:58     |canceled    |NULL                         |1             |1                   |[3415c9f764e478409e8e0660ae816dd2]                                  |2018-07-31 00:00:00|2018-07-31 00:00:00 |[3415c9f764e478409e8e0660ae816dd2]|
|230a1e9f42924d41f37fd22a1d4a9707|4d59cc2a2e7bb6c0a851725f5888a9b5|2018-09-06 14:50:07     |canceled    |NULL                         |1             |1                   |[3415c9f764e478409e8e0660ae816dd2]                                  |2018-07-31 00:00:00|2018-07-31 00:00:00 |[3415c9f764e478409e8e0660ae816dd2]|
|262e1f1e26e92e86375f86840b4ffd63|0f2335c85eae6c232fa46499d5e1e3d2|2018-06-11 16:51:47     |delivered   |2018-06-26 20:03:32          |1             |1                   |[48198628b2d43ed394089750acc59c3f]                                  |2018-06-27 00:00:00|2018-06-27 00:00:00 |[48198628b2d43ed394089750acc59c3f]|
|262e1f1e26e92e86375f86840b4ffd63|b059ee4de278302d550a3035c4cdb740|2018-10-16 20:16:02     |canceled    |NULL                         |1             |1                   |[48198628b2d43ed394089750acc59c3f]                                  |2018-06-27 00:00:00|2018-06-27 00:00:00 |[48198628b2d43ed394089750acc59c3f]|
|3158fc4f60ca92412de397461b64cee3|2bf9fdd42a3609f2c440bec186b10ff7|2018-08-21 14:30:46     |delivered   |2018-08-27 17:22:45          |1             |1                   |[68a97595d96f3890eb24bd5bd2654339]                                  |2018-08-28 00:00:00|2018-08-28 00:00:00 |[68a97595d96f3890eb24bd5bd2654339]|
|3158fc4f60ca92412de397461b64cee3|0a472c47d928bf4cd8b6a7a30345eeb7|2018-08-30 10:14:00     |canceled    |NULL                         |1             |1                   |[68a97595d96f3890eb24bd5bd2654339]                                  |2018-08-28 00:00:00|2018-08-28 00:00:00 |[68a97595d96f3890eb24bd5bd2654339]|
|391d6062da3dd65b4de4524f28c478de|4c8b9947280829d0a8b7e81cc249b875|2018-08-09 14:54:47     |canceled    |NULL                         |1             |1                   |[18071cb247f057c348988037fa94a0cd]                                  |2018-08-02 00:00:00|2018-08-02 00:00:00 |[18071cb247f057c348988037fa94a0cd]|
|391d6062da3dd65b4de4524f28c478de|27667a063cb59b5d987a5a71c192cce5|2018-08-27 19:54:54     |canceled    |NULL                         |1             |1                   |[18071cb247f057c348988037fa94a0cd]                                  |2018-08-02 00:00:00|2018-08-02 00:00:00 |[18071cb247f057c348988037fa94a0cd]|
|46450c74a0d8c5ca9395da1daac6c120|53c71d3953507c6239ff73917ed358c9|2018-07-24 20:41:01     |delivered   |2018-08-02 18:41:16          |1             |1                   |[08528f70f579f0c830189efc523d2182]                                  |2018-08-03 00:00:00|2018-08-03 00:00:00 |[08528f70f579f0c830189efc523d2182]|
|46450c74a0d8c5ca9395da1daac6c120|03310aa823a66056268a3bab36e827fb|2018-08-07 16:33:59     |canceled    |NULL                         |1             |1                   |[08528f70f579f0c830189efc523d2182]                                  |2018-08-03 00:00:00|2018-08-03 00:00:00 |[08528f70f579f0c830189efc523d2182]|
|46450c74a0d8c5ca9395da1daac6c120|7813842ae95e8c497fc0233232ae815a|2018-08-17 20:06:36     |canceled    |NULL                         |1             |1                   |[08528f70f579f0c830189efc523d2182]                                  |2018-08-03 00:00:00|2018-08-03 00:00:00 |[08528f70f579f0c830189efc523d2182]|
|4e1554d1a2dcb38dcf22770eb7390fe1|d351ad232c9e018edafa9f34f5d03e63|2018-07-30 16:36:03     |delivered   |2018-08-07 20:32:42          |1             |1                   |[fbb7c6f69326ad5bf986c099bedefdb4]                                  |2018-08-08 00:00:00|2018-08-08 00:00:00 |[fbb7c6f69326ad5bf986c099bedefdb4]|
|4e1554d1a2dcb38dcf22770eb7390fe1|4608a27e9e60c05b054631def491e7af|2018-08-28 08:10:22     |canceled    |NULL                         |1             |1                   |[fbb7c6f69326ad5bf986c099bedefdb4]                                  |2018-08-08 00:00:00|2018-08-08 00:00:00 |[fbb7c6f69326ad5bf986c099bedefdb4]|
|50c7adf7c25188cf27f66e1cfe278fad|97aeae7e7b1d8a32cf3f26c3946eab1d|2018-07-22 22:09:10     |delivered   |2018-08-04 16:46:56          |1             |1                   |[b370661a9286b652f0ee547c13cb03d1]                                  |2018-08-05 00:00:00|2018-08-05 00:00:00 |[b370661a9286b652f0ee547c13cb03d1]|
|50c7adf7c25188cf27f66e1cfe278fad|d2bc174d5c413f457a21db6899afb682|2018-08-09 09:50:42     |canceled    |NULL                         |1             |1                   |[b370661a9286b652f0ee547c13cb03d1]                                  |2018-08-05 00:00:00|2018-08-05 00:00:00 |[b370661a9286b652f0ee547c13cb03d1]|
|5c96017028584678dd28c139566b87c0|48d94e7406a8d5cbf7505590d86ff0ea|2018-03-22 11:30:05     |delivered   |2018-03-29 15:53:09          |1             |1                   |[d25026282e14fc531f0711246e121cc2]                                  |2018-03-30 00:00:00|2018-03-30 00:00:00 |[d25026282e14fc531f0711246e121cc2]|
|5c96017028584678dd28c139566b87c0|ebc94658c583ab37ad4f8e9091c4bef2|2018-04-14 08:22:43     |delivered   |2018-04-30 20:39:01          |1             |1                   |[d25026282e14fc531f0711246e121cc2]                                  |2018-03-30 00:00:00|2018-03-30 00:00:00 |[d25026282e14fc531f0711246e121cc2]|
|634420a0ea42302205032ed44ac7fccc|b115422b830bf2840fccf6f0d6678ab2|2018-08-16 13:09:43     |delivered   |2018-08-22 19:20:40          |1             |1                   |[8b8f495d30fca09fdc8312e96de1bc47]                                  |2018-08-23 00:00:00|2018-08-23 00:00:00 |[8b8f495d30fca09fdc8312e96de1bc47]|
|634420a0ea42302205032ed44ac7fccc|616fa7d4871b87832197b2a137a115d2|2018-10-01 15:30:09     |canceled    |NULL                         |1             |1                   |[8b8f495d30fca09fdc8312e96de1bc47]                                  |2018-08-23 00:00:00|2018-08-23 00:00:00 |[8b8f495d30fca09fdc8312e96de1bc47]|
|6ba987d564bad1f9da8e14b9d3b71c8f|68f238efe64d771f8529c4689219e854|2018-08-15 12:24:08     |delivered   |2018-08-23 19:45:50          |1             |1                   |[b54d02f7f1520b3995f84b77ab0dacb3]                                  |2018-08-24 00:00:00|2018-08-24 00:00:00 |[b54d02f7f1520b3995f84b77ab0dacb3]|
|6ba987d564bad1f9da8e14b9d3b71c8f|c8c528189310eaa44a745b8d9d26908b|2018-08-28 20:05:14     |canceled    |NULL                         |1             |1                   |[b54d02f7f1520b3995f84b77ab0dacb3]                                  |2018-08-24 00:00:00|2018-08-24 00:00:00 |[b54d02f7f1520b3995f84b77ab0dacb3]|
|6bb7c9ac69dc13b436f413acec41a1b6|177200d363504ea94b5064b05929e2e6|2018-07-19 16:22:41     |delivered   |2018-07-27 17:15:46          |1             |1                   |[63c51abb0488ed1346fe3215f1571f15]                                  |2018-07-28 00:00:00|2018-07-28 00:00:00 |[63c51abb0488ed1346fe3215f1571f15]|
|6bb7c9ac69dc13b436f413acec41a1b6|756fc608f67478946b31c752681f27be|2018-08-14 08:14:45     |canceled    |NULL                         |1             |1                   |[63c51abb0488ed1346fe3215f1571f15]                                  |2018-07-28 00:00:00|2018-07-28 00:00:00 |[63c51abb0488ed1346fe3215f1571f15]|
|76e5f3bca2b1f5c510c41563c2ea31a4|9e119efc7690fb6c238eca967793fd34|2018-08-18 15:26:01     |delivered   |2018-08-24 18:48:40          |1             |1                   |[56647f8fbe7430f42719c0510d99e636]                                  |2018-08-25 00:00:00|2018-08-25 00:00:00 |[56647f8fbe7430f42719c0510d99e636]|
|76e5f3bca2b1f5c510c41563c2ea31a4|21a00b08cbeb5716bbb66105e3dbd850|2018-09-10 17:51:25     |canceled    |NULL                         |1             |1                   |[56647f8fbe7430f42719c0510d99e636]                                  |2018-08-25 00:00:00|2018-08-25 00:00:00 |[56647f8fbe7430f42719c0510d99e636]|
|8fe6fc853d687dac18df5b163f84d438|9c9c501f71dcf81d14d006826972733a|2018-06-29 11:43:13     |delivered   |2018-07-13 13:06:53          |1             |1                   |[8a90511249a72061a421c9bbb7a6f45f]                                  |2018-07-14 00:00:00|2018-07-14 00:00:00 |[8a90511249a72061a421c9bbb7a6f45f]|
|8fe6fc853d687dac18df5b163f84d438|a805d7a514bcde0719f99ddf2a3bb31d|2018-08-17 14:17:56     |canceled    |NULL                         |1             |1                   |[8a90511249a72061a421c9bbb7a6f45f]                                  |2018-07-14 00:00:00|2018-07-14 00:00:00 |[8a90511249a72061a421c9bbb7a6f45f]|
|91544d22848a922381b73b5e21ad58ff|57a7b18332c1b9b26d96e35379af3a38|2018-08-06 19:25:14     |shipped     |NULL                         |1             |1                   |[e5b48a584cec8406e2722967491b4627]                                  |2018-08-26 00:00:00|2018-08-26 00:00:00 |[e5b48a584cec8406e2722967491b4627]|
|91544d22848a922381b73b5e21ad58ff|bb8edfe0742a6a0279b7dff848289568|2018-08-30 10:24:34     |canceled    |NULL                         |1             |1                   |[e5b48a584cec8406e2722967491b4627]                                  |2018-08-26 00:00:00|2018-08-26 00:00:00 |[e5b48a584cec8406e2722967491b4627]|
|9c3af16efacb7aa06aa3bc674556c5d6|b2b8934746a9afa7b38c8c1f88268ecb|2018-08-02 12:06:07     |delivered   |2018-08-13 21:38:56          |1             |1                   |[e6acae33a98861be63cf635525330891]                                  |2018-08-14 00:00:00|2018-08-14 00:00:00 |[e6acae33a98861be63cf635525330891]|
|9c3af16efacb7aa06aa3bc674556c5d6|5aac76cf7b07dd06fa4d50bf461d2f40|2018-09-25 11:59:18     |canceled    |NULL                         |1             |1                   |[e6acae33a98861be63cf635525330891]                                  |2018-08-14 00:00:00|2018-08-14 00:00:00 |[e6acae33a98861be63cf635525330891]|
|af5454198a97379394cacf676e1e96cb|73a8ed1078e1d475d2b1fb7216a52e1a|2018-08-10 10:39:43     |delivered   |2018-08-17 21:21:58          |1             |1                   |[4548534449b1f572e357211b90724f1b]                                  |2018-08-18 00:00:00|2018-08-18 00:00:00 |[4548534449b1f572e357211b90724f1b]|

### Cell code 12A: Trực quan hóa lịch sử khách hàng thuộc 32 nhóm

- **Mục đích:** Trực quan hóa số đơn và số lượt review_id lặp trong lịch sử các khách hàng liên quan.
- **Vì sao:** Không nên vẽ trực tiếp từng `customer_unique_id` vì mã dài và khó đọc.
- **Giúp ích:** Quan sát phân bố hành vi mua của nhóm khách có review bất thường.

In [20]:
# Cell code 12A: Trực quan hóa lịch sử khách hàng thuộc 32 nhóm
import hvplot.pandas

target_customer_pd = target_summary.select(
    "customer_unique_id",
    "tong_so_don",
    "tong_so_dong_review",
    "so_review_id_khac_nhau",
    "so_luot_review_id_lap"
).toPandas()

order_count_dist = (
    target_customer_pd.groupby("tong_so_don")
    .size()
    .reset_index(name="Số khách hàng")
    .rename(columns={"tong_so_don": "Tổng số đơn"})
    .sort_values("Tổng số đơn")
)

customer_orders_plot = order_count_dist.hvplot.bar(
    x="Tổng số đơn",
    y="Số khách hàng",
    width=900,
    height=400,
    title="Phân bố số đơn của khách hàng thuộc 32 nhóm",
    ylabel="Số khách hàng"
).opts(hooks=[black_chart_text])

repeat_review_dist = (
    target_customer_pd.groupby("so_luot_review_id_lap")
    .size()
    .reset_index(name="Số khách hàng")
    .rename(columns={"so_luot_review_id_lap": "Số lượt review_id lặp"})
    .sort_values("Số lượt review_id lặp")
)

repeat_review_plot = repeat_review_dist.hvplot.bar(
    x="Số lượt review_id lặp",
    y="Số khách hàng",
    width=900,
    height=400,
    title="Số lượt review_id lặp trong lịch sử từng khách hàng",
    ylabel="Số khách hàng"
).opts(hooks=[black_chart_text])

display(
    pn.Column(
        customer_orders_plot,
        repeat_review_plot,
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

Column(styles={'background': 'white', ...})
    [0] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=900)

##Nhận xét:
- Đa số review xuất hiện ở đơn đã mua và giao trước đó, rồi cùng review_id lại xuất hiện ở đơn mua sau.

### Cell code 13: So nội dung các dòng review cùng ID

- **Mục đích:** Đối chiếu điểm, tiêu đề, nội dung và thời gian của các dòng cùng review_id.
- **Vì sao:** Nội dung khác nhau và nội dung giống nhau dẫn tới cách xử lý khác nhau.
- **Giúp ích:** Tránh nhầm dòng liên kết lặp thành nhiều bình luận mới.

In [21]:
review_comparison = spark.sql("""
    SELECT
        review_id,
        COUNT(*) AS so_dong,
        COUNT(DISTINCT order_id) AS so_order_id,
        COUNT(DISTINCT to_json(named_struct('v', review_score))) AS so_gia_tri_diem,
        COUNT(DISTINCT to_json(named_struct('v', review_comment_title))) AS so_gia_tri_tieu_de,
        COUNT(DISTINCT to_json(named_struct('v', review_comment_message))) AS so_gia_tri_noi_dung,
        COUNT(DISTINCT to_json(named_struct('v', review_creation_date))) AS so_gia_tri_ngay_tao,
        COUNT(DISTINCT to_json(named_struct('v', review_answer_timestamp))) AS so_gia_tri_luc_tra_loi,
        COUNT(DISTINCT to_json(named_struct(
            'score', review_score,
            'title', review_comment_title,
            'message', review_comment_message,
            'created', review_creation_date,
            'answered', review_answer_timestamp
        ))) AS so_phien_ban_review_khac_nhau
    FROM reviews
    WHERE review_id IS NOT NULL
    GROUP BY review_id
    HAVING COUNT(*) > 1
""").cache()

review_comparison.createOrReplaceTempView("review_comparison")

print("TỔNG HỢP TOÀN BỘ REVIEW_ID LẶP")
spark.sql("""
    SELECT
        COUNT(*) AS so_nhom_review_id_lap,
        SUM(so_dong) AS tong_so_dong,
        SUM(CASE WHEN so_phien_ban_review_khac_nhau = 1 THEN 1 ELSE 0 END) AS nhom_co_review_giong_het,
        SUM(CASE WHEN so_phien_ban_review_khac_nhau > 1 THEN 1 ELSE 0 END) AS nhom_co_review_khac_nhau,
        SUM(CASE WHEN so_gia_tri_diem > 1 THEN 1 ELSE 0 END) AS nhom_khac_diem,
        SUM(CASE WHEN so_gia_tri_tieu_de > 1 THEN 1 ELSE 0 END) AS nhom_khac_tieu_de,
        SUM(CASE WHEN so_gia_tri_noi_dung > 1 THEN 1 ELSE 0 END) AS nhom_khac_noi_dung,
        SUM(CASE WHEN so_gia_tri_ngay_tao > 1 THEN 1 ELSE 0 END) AS nhom_khac_ngay_tao,
        SUM(CASE WHEN so_gia_tri_luc_tra_loi > 1 THEN 1 ELSE 0 END) AS nhom_khac_luc_tra_loi
    FROM review_comparison
""").show(truncate=False)

print("KẾT QUẢ CỦA TỪNG REVIEW_ID LẶP")
review_comparison.orderBy("review_id").show(
    review_comparison.count(), truncate=False
)

print("BẢN GHI GỐC CỦA CÁC NHÓM CÓ TRƯỜNG REVIEW KHÁC NHAU")
different_reviews = spark.sql("""
    SELECT
        r.review_id,
        r.order_id,
        r.review_score,
        r.review_comment_title,
        r.review_comment_message,
        r.review_creation_date,
        r.review_answer_timestamp
    FROM reviews r
    JOIN review_comparison c ON r.review_id = c.review_id
    WHERE c.so_phien_ban_review_khac_nhau > 1
    ORDER BY r.review_id, r.review_creation_date, r.order_id
""")

different_reviews.show(different_reviews.count(), truncate=False)

TỔNG HỢP TOÀN BỘ REVIEW_ID LẶP
+---------------------+------------+------------------------+------------------------+--------------+-----------------+------------------+------------------+---------------------+
|so_nhom_review_id_lap|tong_so_dong|nhom_co_review_giong_het|nhom_co_review_khac_nhau|nhom_khac_diem|nhom_khac_tieu_de|nhom_khac_noi_dung|nhom_khac_ngay_tao|nhom_khac_luc_tra_loi|
+---------------------+------------+------------------------+------------------------+--------------+-----------------+------------------+------------------+---------------------+
|789                  |1603        |789                     |0                       |0             |0                |0                 |0                 |0                    |
+---------------------+------------+------------------------+------------------------+--------------+-----------------+------------------+------------------+---------------------+

KẾT QUẢ CỦA TỪNG REVIEW_ID LẶP
+--------------------------------+-------+-----------+---------------+------------------+-------------------+-------------------+----------------------+-----------------------------+
|review_id                       |so_dong|so_order_id|so_gia_tri_diem|so_gia_tri_tieu_de|so_gia_tri_noi_dung|so_gia_tri_ngay_tao|so_gia_tri_luc_tra_loi|so_phien_ban_review_khac_nhau|
+--------------------------------+-------+-----------+---------------+------------------+-------------------+-------------------+----------------------+-----------------------------+
|00130cbe1f9d422698c812ed8ded1919|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0115633a9c298b6a98bcbe4eee75345f|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0174caf0ee5964646040cd94e15ac95e|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|017808d29fd1f942d97e50184dfb4c13|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0254bd905dc677a6078990aad3331a36|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0288d42bef3dfe36930740c9588a570f|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|02aa7f5f75e964e3c7efa59a1f515281|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|034528cb00b6bc981847acafbdf2ae0b|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|03a6a25db577d0689440933055111897|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0467560f511c516ddaa54a60edb0c291|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|047fd109ced39e02296f6aeb74f6a6f1|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0498e9722f8757426c3c3ee0b91e666d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0501aab2f381486c36bf0f071442c0c2|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0546d398a833d4c33dec480bedeecfbd|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0655af56f10bc3ef8e3810610828f294|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|06e327fb381850fdd69fba40ad61b2f2|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0837bc8fa2cb75353513858b3bb5be1d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|08528f70f579f0c830189efc523d2182|3      |3          |1              |1                 |1                  |1                  |1                     |1                            |
|08531aa0b3844944e7aeef53530f8598|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|08a86da22498172adb6cefaa99fdfaf7|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|090aa2980b0aea78cd1ae73447d7d55b|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|09534ea272eea99209ff37c5c348ceb1|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|09b871b3f4f85d3595cb37054a9105f1|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0a2d1206f8b2473cd3ddf69b51bca98a|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0a3b875d00f437f25215e0ac942efca2|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0a3caf6324edd5158b342ee5a0886271|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0a6ec47c5d78509672e16b95efcff53b|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0ad57b9e68d4d34814464772b6de54fe|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0ad87184dc47c36db717b98e8baca9cc|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0b51553f3cd2e9606b9c0f25667dc5bb|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0b9af3c12843b743f612ca8abbc33e83|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0bb958acd9e40d9348635c75013f7b19|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0c0b58839bdc7b7d49396ddf94a3dbf7|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0c1f10775ef729e60b56d9c6dcc47736|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0c2915e69ee09c18b9c15b8035bdc5ff|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0c76e7a547a531e7bf9f0b99cba071c1|3      |3          |1              |1                 |1                  |1                  |1                     |1                            |
|0c8e7347f1cdd2aede37371543e3d163|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0e18d426420da859dfd6fb4beaba9efe|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0e249472bec47b0c4b88a8e8bfa8d241|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0ec0f24aa34a9b25fb0f7b32034965ce|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0efebc2c5add22c5b45867716919dcdd|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0f45a7a6cab5ac1c9cc25ce1eb2357d2|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|0ffae99e57188428340c206afb957a1c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|10398bad17ab17c451c39a0b2c47464c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|105facb42b5b9147996f0b1b6fbf7b80|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|10bca0461c36ef14701fa28971d0cdb5|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|11912dbae5f169782098a20fc51c0b33|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|11c94569cabc7d493a0aa1c5cd1dbfb4|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|12476f0c366e9de86c46fbced6372d92|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1258a603cc9e4897f7955ab218c83b8c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|12f2fd663de5670387805fd70ece2e21|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|135df63f4871bf893d89ca67df0f921c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|13b2872ada20991c4f52ccb141cb1705|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|13cc14a5f7a442a1ecce8f32b463e242|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|13d45c97ae78e0ef1361835b8944b7b0|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1439640ba4905dc2f98188cad2a77154|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1442a23fe4555fda0f7c7eb7ba5ae3b1|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|15c9136f43468a8428316d9871eaf14d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|15daa9db89623052d7b25d96ed14686d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|161160f7f3602ec0de9cd583b62b3b15|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|167b40b617e650de2c473d70baae2e65|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|168b708c0e1d90f89c9737b1160121d6|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1708c3eec64152cb52fe56bb3abcf257|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|17592266cd3216a98665ebfd6365843a|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|176a37898b45f9db0b8de7641973bf53|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1775bd097716d67420d128df008252eb|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|17939259ccc419f355fb4a148151fb00|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|18071cb247f057c348988037fa94a0cd|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|183808dc516fab3df74b087310299cf0|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|19194f53840fc6c2857dd8809972a209|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|193d73d33b656807084215db91b23b8c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1961cafe1d1cbd4cc701c2f0160467ff|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|19d60869413aa63834affc9ecc9d9f90|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1a6be4c794d5e3da242a364f6a98163f|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1b5dc3da2372e9bb5518cd37cd9a9354|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1b8df55d40e129a4003858afb671129c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1bda8c20e199f7c2e9a342600031518b|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1c0c84f0e3132c3af0a17f0aa4987879|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1c7a92108afc9782646581517fbb2808|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1c7b8b15de9a2eff8caac4ece3fc0f49|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1c7e1a24358cea9db1eecc6987843a28|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1c9023a88f4effba4abbf114c58bedba|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1ce9388b1a3ad76f5f1a64f208a90fce|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1d5b8cc3cac5888ebfc80a0dcd337f07|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1dee9d450a2b8533d2085cef898ca4a2|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1e3fb3520c0e1e9c12b0dc943f7d437b|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1ed01e8f777018a33227be5073a82e8d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1ed134d3e8e587c1589c338712516757|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1ef17c31c6a710e3cee7853fb387dcc3|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1f1702781508ddd2fc0020f6c691d600|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1f5aa5d7c3ee7895e4d223797b5a5f2d|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1f80ddc1e47fa27e028f8d94684375d8|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1f97f75959fdde611d52fde0a4ef310c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1f997992c19d44fe5049ec91f13ccd34|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|1fb4ddc969e6bea80e38deec00393a6f|3      |3          |1              |1                 |1                  |1                  |1                     |1                            |
|202b5f44d09cd3cfc0d6bd12f01b044c|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|20361385529351bec8dbcc659449cf2f|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|206ac3e1651d98d3a5b41e6b83409168|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|20dbd899791a670bf2dafabf0243f6ee|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |
|2172867fd5b1a55f98fe4608e1547b4b|3      |3          |1              |1                 |1                  |1                  |1                     |1                            |
|22a299893c5cee48be41d8fab8804e6e|2      |2          |1              |1                 |1                  |1                  |1                     |1                            |

### Cell code 13A: Trực quan hóa cấu trúc review_id lặp

- **Mục đích:** Trực quan hóa số order_id và số phiên bản nội dung của từng review_id lặp.
- **Vì sao:** Cell 13 có bảng chi tiết 789 nhóm nên rất khó nhìn bằng `.show()`.
- **Giúp ích:** Xác nhận trực quan review_id lặp chủ yếu khác order_id chứ không tạo phiên bản nội dung mới.

In [22]:
# Cell code 13A: Trực quan hóa cấu trúc review_id lặp
import hvplot.pandas

review_compare_pd = review_comparison.select(
    "review_id",
    "so_dong",
    "so_order_id",
    "so_phien_ban_review_khac_nhau"
).toPandas()

order_id_dist = (
    review_compare_pd.groupby("so_order_id")
    .size()
    .reset_index(name="Số review_id")
    .rename(columns={"so_order_id": "Số order_id"})
    .sort_values("Số order_id")
)

order_ids_plot = order_id_dist.hvplot.bar(
    x="Số order_id",
    y="Số review_id",
    width=850,
    height=400,
    title="Số order_id liên kết với mỗi review_id bị lặp",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

version_dist = (
    review_compare_pd.groupby("so_phien_ban_review_khac_nhau")
    .size()
    .reset_index(name="Số review_id")
    .rename(columns={"so_phien_ban_review_khac_nhau": "Số phiên bản review khác nhau"})
    .sort_values("Số phiên bản review khác nhau")
)

review_versions_plot = version_dist.hvplot.bar(
    x="Số phiên bản review khác nhau",
    y="Số review_id",
    width=850,
    height=400,
    title="Số phiên bản nội dung trong mỗi review_id bị lặp",
    ylabel="Số review_id"
).opts(hooks=[black_chart_text])

display(
    pn.Column(
        order_ids_plot,
        review_versions_plot,
        styles={"background": "white", "color": "black", "padding": "12px"}
    )
)

Column(styles={'background': 'white', ...})
    [0] HoloViews(Bars, height=400, sizing_mode='fixed', width=850)
    [1] HoloViews(Bars, height=400, sizing_mode='fixed', width=850)

##Nhận xét:
- Có cả 789 review_id lặp đều có điểm số, tiêu đề, nội dung và hai mốc thời gian giống hệt nhau; chỉ order_id khác. Vì vậy, kết quả không chứng minh giả thuyết đây là các review mới hay các phiên bản được chỉnh sửa.